### ISSUE TITLE
Zbavenie sa nesprávnej meta sekcie v podaniach slovensko.sk

### ISSUE THREAD

**Issue by mpinter** [bratislava/konto.bratislava.sk#1050]
(presunute z archivovaneho repozitara)

Meta ktorá je pod MessageContainer je dnes správna, okrem nej však v xml obálke máme aj Meta sekciu ktorá je hardcoded pre každý formulár a zrejme rpíliš nedáva zmysel.

Treba sa buď zbaviť celej sekcie, alebo (pokiaľ toto nei je možné), ju skladať dynamicky pre každé podanie, rovnakú ako vo vnútri MessageContainer-a.

Príklad: Meta hardcoded v xmlTemplate:

<E-form xmlns:E-form="http://schemas.gov.sk/form/00603481.stanoviskoKInvesticnemuZameru/0.8"
  xmlns="http://schemas.gov.sk/form/00603481.stanoviskoKInvesticnemuZameru/0.8"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://schemas.gov.sk/form/00603481.stanoviskoKInvesticnemuZameru/0.8 schema.xsd">
  <Meta>
    <ID>00603481.stanoviskoKInvesticnemuZameru</ID>
    <Name>Žiadosť o stanovisko k investičnému zámeru</Name>
    <Gestor>Martin Pinter</Gestor>
    <RecipientId />
    <Version>0.8</Version>
    <ZepRequired>0</ZepRequired>
    <EformUuid>string</EformUuid>
    <SenderID>mailto:</SenderID>
  </Meta>
  <Body>
    ...
  </Body>
</E-form>
Meta na rovnakom formulári vo vnútri MessageContainer:

                <MessageContainer xmlns="http://schemas.gov.sk/core/MessageContainer/1.0">
                  <MessageId>${data.id}</MessageId>
                  <SenderId>${senderId}</SenderId>
                  <RecipientId>${
                    process.env.NASES_RECIPIENT_URI ?? ''
                  }</RecipientId>
                  <MessageType>${pospID}</MessageType>
                  <MessageSubject>${subject}</MessageSubject>
                  <Object Id="${data.id}" IsSigned="${
                    isSigned ? 'true' : 'false'
                  }" Name="${schema.formName}" Description="${
                    formDescription ?? ''
                  }" Class="FORM" MimeType="${mimeType}" Encoding="${encoding}">${message}</Object>
    ${attachments}
                </MessageContainer>

**Comment by MarekBodingerBA** [comment]
@mpinter Toto sa netýka iba tých starých formov (staré XML)?

**Comment by mpinter** [comment]
Tyka, zatvaram, coskoro nebude relevant.
