### ISSUE TITLE
DzN - skrytie dzn pre PO a SZCO

### ISSUE THREAD

**Issue by ZdenkoPek** [bratislava/konto.bratislava.sk#1232]
**Čo ideme robiť**
Skryť položku Dane a poplatky pre prihlásených používateľov, ktorí sú SZČO alebo PO.

**Prečo to ideme robiť**
SZČO a PO nedisponuju zobrazenim dane a ziadna ina moznost zobrazenia dane alebo poplatkov pre nich neexistuje.

**Pre koho to robíme**
Interné potreby

**Dáta**
Žiadne

**Prerekvizity, závislosti**
Žiadne

**Akceptačné kritériá**
- [x] Po prihlásení SZCO nevidí v navigácii Dane a poplatky
- [x] Po prihlaseni PO nevidi v navigacii Dane a poplatky
- [x] V pripade pokusu o otvorenie URL napr. /dane-a-poplatky bude presmerovaní na 404

**Dokumentácia**
![Image](https://github.com/user-attachments/assets/2d9052de-53de-4974-845e-aa6a2852c453)

**Comment by MarekBodingerBA** [comment]
> V pripade pokusu o otvorenie URL napr. /dane-a-poplatky bude presmerovaní na https://konto.bratislava.sk/
Toto by malo hodiť skôr 404.

**Comment by ZdenkoPek** [comment]
> > V pripade pokusu o otvorenie URL napr. /dane-a-poplatky bude presmerovaní na https://konto.bratislava.sk/
> > Toto by malo hodiť skôr 404.

Preco si myslis?

**Comment by JanaJurkovic** [comment]
@jitka1997 odhad
@ZdenkoPek ping

**Comment by ZdenkoPek** [comment]
Otestovane SZCO aj PO, je to ok.
