### ISSUE TITLE
Cognito - QUEUE_IDENTITY_CARD

### ISSUE THREAD

**Issue by ZdenkoPek** [bratislava/konto.bratislava.sk#1240]
V cognite je priblizne 45 pouzivatelov v stave QUEUE_IDENTITY_CARD. Bolo by super, keby sa to podarilo precistit a overit ich.

**Comment by erehulka** [comment]
Tí čo by mali byť overení tak sú, ostatným som to zamietol, už teda nikto nie je v QUEUE.
