### ISSUE TITLE
Pripraviť dizajn pre FO: Vznik oznámenia

### ISSUE THREAD

**Issue by JanaJurkovic** [bratislava/konto.bratislava.sk#1412]
To do:
- [ ] doplniť landing page
- [ ] vyriešiť ďalších poplatníkov

**Comment by JanaFecenkova** [comment]
@petra-trananhova na začiatku budúceho týždňa chceme zahrnúť copywriterku, budeme to mať pripravené do vtedy? 
Na to bude potrebné: 
- [ ] doplniť landing page
- [ ] vyriešiť poplatníkov 
Je tam ešte niečo čo eviduješ?
