### ISSUE TITLE
DzN - nezobrazovanie QR kodu na mobile

### ISSUE THREAD

**Issue by ZdenkoPek** [bratislava/konto.bratislava.sk#1430]
**Čo ideme robiť**
V pripade mobilneho zariadenia (mobil) schovame moznost platby QR kodom. V tabletoch by sme QR kod zobrazovali.

**Prečo to ideme robiť**
Zobrazovanie QR kodu na mobilnom zariadeni nema logicky vyznam, kedze na naskenovanie QR kodu je potrebne mobilne zariadenie.

**Pre koho to robíme**
ziadne

**Dáta**
ziadne

**Akceptačné kritériá**
- [ ] v pripade zobrazenia DzN na mobile sa nezobrazi moznost uhrady QR kodom
- [ ] v pripade zobrazenia DzN na tablete sa QR kod zobrazi
- [ ] v pripade zobrazenia DzN na desktopre sa QR kod zobrazi

**Dokumentácia**
ziadne

**Comment by JanaJurkovic** [comment]
Update: zistili sme, že banky podporujú zoskenovanie QRkódu z obrázku. Takže by sme to tam na teraz nechali. @ZdenkoPek

**Comment by ZdenkoPek** [comment]
Uzatvaram nakolko niektore banky dokazu uploadnut obrazok QR kodu a na jeho zaklade vygenerovat platobny prikaz. Podstatne vsak bude o tomto povedat pri platbe dane, aby bolo zrejme na co sluzi stiahnutie QR kodu.
