### ISSUE TITLE
DzN - odstranenie zltej hlasky

### ISSUE THREAD

**Issue by ZdenkoPek** [bratislava/konto.bratislava.sk#1433]
**Čo ideme robiť**
Odstrániť žlté hlásenie: Ak ste platili prevodom alebo QR kódom platbu pravdepodobne zaznamenáme až po 24.5. zo stránky dane pre rok 2024, 2023 a iných rokov.

**Prečo to ideme robiť**
Toto hlásenie je už neaktuálne

**Pre koho to robíme**
Interné potreby

**Dáta**
Žiadne

**Prerekvizity, závislosti**
Žiadne

**Akceptačné kritériá**
- [ ] po otvorení stránky zaplatenia dane v danom roku sa hlásenie nezobrazuje

**Dokumentácia**
![Image](https://github.com/user-attachments/assets/bcc85c02-9c71-469e-adc0-16ee44bf1f1d)

Dakujem
Z

**Comment by JanaJurkovic** [comment]
Odhadnuté, dáme do šprintu 2
