### ISSUE TITLE
DzN - odlisenie platieb bankovy prevod a qr kod

### ISSUE THREAD

**Issue by ZdenkoPek** [bratislava/konto.bratislava.sk#1435]
**Čo ideme robiť**
Po naskenovaní QR kódu budeme do poľa "Správa pre prijímateľa" dopĺňať popis QR_WEB.

**Prečo to ideme robiť**
Aby sme odlisili platby, ktore k nam prijdu naskenovaním QR kódu a ktoré manuálne zadaným prevodným príkazom.
Aby sme vedeli, ako ľudia reálne platia a v budúcnosti podľa toho robili rozhodnutia (napr. zistíme že neplatia bankovým prevodom, ten potom vyhodíme alebo vieme ako prioritizovať zobrazenie spôsobov platby) 

**Pre koho to robíme**
Pre interné štatistické potreby.

**Dáta**
žiadne

**Akceptačné kritériá**
- [ ] po naskenovaní QR kódu sa v platobnom príkaze bankovej aplikácie v poli Správa pre príjmateľa zobrazí názov QR_WEB

**Dokumentácia**
žiadna

**Prerekvizity**
- [ ] doplnenie správy pre príjemcu aj do papierových rozhodnutí (optional)

**Comment by JanaJurkovic** [comment]
@erehulka prosím odhad do pondelka 25.11.

**Comment by erehulka** [comment]
Vyzerá že to knižnica na generovanie qr kódov to podporuje, teda by to nemalo byť náročné, každopádne sa to prejaví až na nových daniach.

**Comment by ZdenkoPek** [comment]
Pozrel som to na staggingu a je to ok
