### ISSUE TITLE
DzN - odstránenie konštantného symbolu

### ISSUE THREAD

**Issue by ZdenkoPek** [bratislava/konto.bratislava.sk#1538]
V rámci platby dane za nehnutelnosti sa nachadzaju informacie o cisle uctu, VS a KS. Vyjadrenie za danove, pravne a financne je, ze KS nemusime pouzivat. Informaciu o KS odstranime. Odstranime ju aj z generovaneho QR kodu.

![Image](https://github.com/user-attachments/assets/89d699fb-b4a7-447b-9804-6594c7ff447c)

**Comment by ZdenkoPek** [comment]
@MarekBodingerBA po nacitani QR kodu na staggingu sa stale doplna do platobneho prikazu konštantny symbol

**Comment by erehulka** [comment]
@ZdenkoPek QR kódy sú generované pri vytvorení dane, teda bez KS budú až nové dane. Môžeme to testnúť teda tak, že ti zmažem daň na stagingu, nanovo importujem z Norisu a otestuješ ten QR kód.

**Comment by ZdenkoPek** [comment]
> @ZdenkoPek QR kódy sú generované pri vytvorení dane, teda bez KS budú až nové dane. Môžeme to testnúť teda tak, že ti zmažem daň na stagingu, nanovo importujem z Norisu a otestuješ ten QR kód.

jasne tak sprav a daj mi vediet.

**Comment by erehulka** [comment]
Skús teraz, či ti to pôjde bez KS

**Comment by ZdenkoPek** [comment]
> Skús teraz, či ti to pôjde bez KS

uz je to ok. Dakujem
