### ISSUE TITLE
Validovať nový upravený dizajn s dev

### ISSUE THREAD

**Issue by petra-trananhova** [bratislava/konto.bratislava.sk#1588]
**Čo ideme robiť**
- prejsť si v procese dizajnovania obrazovky aj s developerom

**Prečo to ideme robiť**
- aby sme mali istotu, že navrhnuté veci dávajú zmysel po technickej stránke a sú realizovateľsné

**Pre koho to robíme**
- pre produkťákov a devs

**Dáta** -

**Akceptačné kritériá**
- prešli sme si dizajn s Marekom a dohodli sa na prípadných úpravách, tieto úpravy sme si s ním prešli a oddobrili

**Dokumentácia**
- dizajn vo Figme https://www.figma.com/design/LsCdQeJGzjHfOyOSm4juDB/BK-slu%C5%BEby---Komun%C3%A1lny-odpad?node-id=635-25735&t=AAVaKhnmmJWKBVOa-1

**Comment by JanaJurkovic** [comment]
Včera sme si prešli s Marekom, vypadlo z toho tento zápis a ďalšie kroky: https://inovaciebratislava.slack.com/archives/C07HQHABKTJ/p1730204775308049

**Comment by JanaJurkovic** [comment]
Keď zapracujeme veci po testovaní, tak si to treba znova prejsť s Marekom
