### ISSUE TITLE
Nájomné-Nastaviť User management

### ISSUE THREAD

**Issue by ZuzanaHornikova** [bratislava/konto.bratislava.sk#1669]
**Čo ideme robiť**

Nastaviť nový proces pre manažovanie prideľovania prístupov pre SharePoint interný nástroj - už nebudeme prideľovať my pre nich, ale budú si riešiť samostatne cez zvolených zástupcov

- [x] ZH - Získať info od útvarov: kto bude prideľovať prístupy za SNB, SSV (tzv. zástupcov)
- [x] Erik a ZH - krátke "demo" kde a ako sa prideľujú prístupy v SharePoint internom nástroji
- [x] Erik pripraví screenshoty a draft postupu do manuálu
- [x] Erik pridelí vhodné permission pre zvolených zástupcov, aby mohli prideľovať a manažovať prístupy
- [x] ZH revízia návodu 
- [ ] ZH komunikácia na zvolených zástupcov

**Comment by JanaJurkovic** [comment]
updateni task pre Erika čo presne treba spraviť @ZuzanaHornikova

**Comment by erehulka** [comment]
- spísat manuál na prideľovanie povolení
- po odoslaní manuálu prideliť admin role príslušným ľuďom

**Comment by ZuzanaHornikova** [comment]
Za Erika je všetko DONE, vďaka. 
Ešte 2.12. mám call k manuálu s "novými adminmi" - potom issue uzavriem.
