### ISSUE TITLE
Nájomné-Zmena textu v žiadosti

### ISSUE THREAD

**Issue by ZuzanaHornikova** [bratislava/konto.bratislava.sk#1671]
**Čo ideme robiť**
V Sekcii "Iné okolnosti" - doplniť text: Výška nájmu vrátane nájmu s energiami

[Image](https://github.com/user-attachments/assets/4ace6982-87ac-4f1c-98ff-a575fd052552)

Súvisí: https://github.com/bratislava/konto.bratislava.sk/issues/1672

**Comment by MarekBodingerBA** [comment]
Ako to má presne znieť prosím?

**Comment by ZuzanaHornikova** [comment]
Nové znenie:

Uveďte, prosím, maximálnu výšku nájomného (vrátane energií), ktorú dokážete mesačne platiť

**Comment by MarekBodingerBA** [comment]
A to nevadí, že od istého bodu tie žiadosť budú s energiami keď predtým boli bez?

**Comment by ZuzanaHornikova** [comment]
Uz som ich upozornila, ozvem ak by nieco. Dakujem

**Comment by JanaJurkovic** [comment]
@MarekBodingerBA update stavu issue

**Comment by MarekBodingerBA** [comment]
Vrátil som naspäť na "vrátane energií". Do hodiny by malo byť na produkcii.

**Comment by ZuzanaHornikova** [comment]
Perfektné, ďakujem, všetky zmeny schválili, aj [#1672](https://github.com/bratislava/konto.bratislava.sk/issues/1672)
