### ISSUE TITLE
Nájomné-Upraviť v žiadosti sumár - zoznam potrebných dokumentov

### ISSUE THREAD

**Issue by ZuzanaHornikova** [bratislava/konto.bratislava.sk#1672]
V Zozname dokumentov je napísané len Rizikové faktory, ale nie sú rozpísané konkrétne dokumenty podľa toho, čo bolo zakliknuté

--
Neohrozuje launch 16.9.2024  - TBD ešte info od Martina (potrebujú zistiť od inštitúcií akými dokladmi sa môže žiadateľ preukázať) 
výhľadovo výrazná pomôcka pre sociálne šetrenie - potrebujeme vedieť čo si žiadateľ zaklikol - čo sa má presne kontrolovať

--- 
Doplnenie zadania 26.9.2024:

1. Sekcia> rizikové faktory - v prípade zakliknutia možnosti:

1.1. Opustenie Ústavu na výkon väzby a Ústavu na výkon trestu odňatia slobody v uplynulých 3 rokoch a skôr
generovať v zozname dokumentov:
DOKLAD: Rozhodnutie/doklad o prepustení z Ústavu na výkon väzby a Ústavu na výkon trestu odňatia slobody alebo resocializačného zariadenia v uplynulých 3 rokoch;

1.2. Opustenie špeciálneho výchovného zariadenia v uplynulých 3 rokoch 
Generovať v zozname dokumentov:
DOKLAD: doklad o opustení špeciálneho výchovného zariadenia v uplynulých 3 rokoch, iba v prípade dobrovoľného pobytu. 

2. Sekcia> súčasné bývanie: 
v prípade zakliknutia možnosti "Bývanie inštitucionálnej starostlivosti"
generovať v zozname dokumentov:
DOKLAD: Doklad o budúcom prepustení z ÚVTOS alebo resocializačného zariadenia (v prípade ak sa Vás táto možnosť týka)

Súvisí s: https://github.com/bratislava/konto.bratislava.sk/issues/1671

**Comment by ZuzanaHornikova** [comment]
![Image](https://github.com/user-attachments/assets/1b008769-9848-42c1-8824-4a7e571de0cb)

**Comment by MarekBodingerBA** [comment]
Má sa meniť aj táto hláška?
![Image](https://github.com/user-attachments/assets/1cd2f2b9-a040-4916-a4ab-73702539f24e)

Resp. má sa zobraziť iba ak je jedna z tých možností zvolená?

Taktiež v "Doplňujúcich informáciách":
![Image](https://github.com/user-attachments/assets/df4a6dbf-a5aa-4eda-80d1-3abb7271e93d)

Má sa toto zobrazovať iba ak je jedna z tých dvoch možností zvolená, alebo už aj keď je "Týkajú sa vás alebo niektorého člena/členky vašej domácnosti rizikové faktory, ktoré zvyšujú sociálno-ekonomickú zraniteľnosť?" "Áno"?

**Comment by ZuzanaHornikova** [comment]
Ahoj Marek, všetko sme si prešli so stakeholdermi - [prikladám ppt ](https://magistratba.sharepoint.com/:p:/s/InnovationTeam/ESYs2FyHd51AvIlb27i83BUBZu8bn9yM4-DoQXzn_beg2A?e=5abcFG)

**Comment by ZuzanaHornikova** [comment]
Ahoj Marek, @MarekBodingerBA dakujem za mna to vyzera super, poslala som staging na stakeholderov

**Comment by ZuzanaHornikova** [comment]
@MarekBodingerBA zmeny schválené, môže ísť do produkcie, vďaka
