### ISSUE TITLE
Cleanup starých DRAFT formulárov

### ISSUE THREAD

**Issue by MarekBodingerBA** [bratislava/konto.bratislava.sk#1734]
Keďže formuláre vytvarajú pri každom otvorení novú inštanciu do databázy navrhujem periodicky vymazávať staré a prázdne formuláre, povedzme, ak je form v stave DRAFT, formDataJson je `null` a je starší ako týždeň.

Netreba zabudnúť aj na cleanup súborov ak sú k nim nejaké nahraté.

**Comment by erehulka** [comment]
https://github.com/bratislava/konto.bratislava.sk/pull/1748
