### ISSUE TITLE
Nájomné-SharePoint-Pridať nové tagy do stĺpca "Stav žiadosti"

### ISSUE THREAD

**Issue by ZuzanaHornikova** [bratislava/konto.bratislava.sk#1771]
**Čo ideme robiť**
Pridať nové tagy do stĺpca "Stav žiadosti"

 texty nových tagov: 

zaslaná na BK
prerokovaná na BK

**Prečo to ideme robiť**
v kontexte [tasku  ](https://github.com/bratislava/konto.bratislava.sk/issues/1670) a potreby filtrovania a exportu dát do Excelu - useri si vedia vytvoriť zobrazenie spĺňajúce ich kritéria a toto exportovať, identifikovali že ešte by potrebovali tieto 2 tagy odrážajúce proces spracovania žiadosti aby si vedeli vytvoriť potrebné datasety

**Pre koho to robíme**
pre stakeholderov (SNB, SSV)

![Image](https://github.com/user-attachments/assets/bdccda38-6bbf-40d4-9125-5504557e0095)

**Comment by ZuzanaHornikova** [comment]
Ahojte, poprosím aby ste v stredu 20.11. na refinemente prešli, zadali na odhad DEV tímu a do najbližšieho sprintu, dakujem
DEV: Erik/Pinto (odhadujem)

**Comment by JanaJurkovic** [comment]
odhadnúť má @erehulka, odhad potrebujeme do planningu v pondelok 25.11.

**Comment by erehulka** [comment]
Toto bude rýchla zmena, dal som 0.5 MD

**Comment by ZuzanaHornikova** [comment]
Od Erika vyriešené, odkomunikovala som stakeholderom v Planneri - po stretnutí 27.11. uzavriem
