### ISSUE TITLE
OLO Taxi - skrátenie sumáru pre zákazku

### ISSUE THREAD

**Issue by barborapuchlova** [bratislava/konto.bratislava.sk#1908]
**Čo ideme robiť**
aktuálne nám na zakazka@olo.sk chodia objednávky OLO Taxi v takom formáte, žekeď sa to vytlačí, zmestí sa to na dve strany. Požadujeme zúžiť zalomenie/zmenu formátu formulára na 1str.

**Prečo to ideme robiť**
Aktuálny formát objednávok OLO Taxi, ktoré sa posielajú na zakazka@olo.sk, sa pri tlači rozkladá na dve strany. To spôsobuje zbytočnú spotrebu papiera, neefektívnu správu dokumentov.

**Pre koho to robíme**
OLO Oddelenie služieb zákazníkom 

**Akceptačné kritériá**
Sumár sa bude dať vytlačiť na jednu stranu

**Comment by JanaJurkovic** [comment]
Sumár sa nedá upravovať - s týmto teda nevieme nič spraviť na našej strane.

**Comment by barborapuchlova** [comment]
odkomunikované, že to nerobíme, že je to defaultné nastavenie pre všetky forms.
