### ISSUE TITLE
Mobilny Chrome - login email/password issues

### ISSUE THREAD

**Issue by mpinter** [bratislava/konto.bratislava.sk#290]
Autofill nefunguje spravne - heslo sa buď nevyplní, alepo vyzerá vyplnene avšak po kliknutí na prihlásenie sa tvári ako prázdny field.

Po vyplneni jedneho fieldu cez autofill a jeho manualnom doplnani sa sprava cudne (zdvojuje znaky, nefunguje delete). Nemame presny scenar ktorym toto zopakovat, verime ze ak vycistime html/css/js login formu natolko aby fungoval autofill hesla mohlo by to vyriesit aj ostatne problemy.

Na desktope aj na (mobilnom) safari funguje správane.

**Comment by JacobMu** [comment]
Snazil som sa zreprodukovat tento bug na desktope (Firefox, Safari, Chrome) a na mobile (Firefox, Chrome a Safari), zial bez uspechu. Email aj heslo sa vyplnilo spravne. Skusal som vymazanie casti heslo, doplnenie hesla. Bez uspechu, ze by sa prejavil vyssie spomenuty problem.
Na vyplnenie hesla bola pouzita nativna funkcionalita prehliadaca alebo nejaky manazer hesiel 3tej strany?
Jedna moznost je, ze by problem mohol byt len v mobilnej aplikacii Chrome.

**Comment by JacobMu** [comment]
Pripadne vie to este niekto iny zreprodukovat?

**Comment by mpinter** [comment]
Touto dobou uz je to urcite CNR, cize beriem ako resolved a zatvaram.
