### ISSUE TITLE
OpenAPI client pre tax backend + cleanup api utils

### ISSUE THREAD

**Issue by mpinter** [bratislava/konto.bratislava.sk#309]
Rovnaký prístup ako pri forms backend. Predpoklad je že toto je posledné API voči ktorému to robíme -  s tax api sa dnes nepracuje, ale po tomto tasku môžeme vyčistiť zvyšok nie-generovaného api kódu.

**Comment by JacobMu** [comment]
PR: https://github.com/bratislava/konto.bratislava.sk/pull/356
