### ISSUE TITLE
Disabled konto - error hlaska

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#323]
Prosim, vytvorme error hlasku pre ludi, ktori si ziadali deaktivovat konto. 

V cognite to Lukas riesi tak, ze prehodi status usera z active na disabled. Chceme tymto ludom, pokial sa budu snazit registrovat/prihlasit s deaktivovanym emailom napisat specificku error hlasku v zneni: 

Konto so zadanou e-mailovou adresou bolo deaktivované. Kontaktujte podporu na info@bratislava.sk, ak si želáte znova ho aktivovať.

**Comment by mpinter** [comment]
Extra info - este sme nemysleli na stav kedy je pouzivatel uz prihlaseny (ma ulozeny platny token) ale ucet ma uz disabled. Ak by toto neslo nejako rozumne priamociaro mozeme si povedat ze je to edgecase ktory neriesime, ale v idealnom pripade tu chceme zobrazit rovnaky wording ako vyssie ale ako error page,podobne ako mame nejaku 404 stranku.

**Comment by MartinaMihalkovicova** [comment]
keďže nemám deaktivovane konto, neviem testnut
