### ISSUE TITLE
Accessibility upravy vnutri v konte

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#324]
S Radom sme si prechádzali konto a potrebujeme spraviť pár drobných úprav kvôli prístupnosti

- [x] - zadať `<title>` element v znení "Bratislavské konto"
- [x] - doplniť k ilustráciám prázdne alt texty
- [x] - logo link v hlavičke - použiť komponent, ktorý používame všade (máme implementovaný Button)
- [x] - zvýrazniť focus pri profilovom menu (MM Martina) - momentálne ho nevidno
- [x] - menu (úvod, služby, dane, pomoc) - spraviť ho tak, aby bolo ovládateľné aj šípkami keď som na focuse
- [ ] - v buttone s iniciálmi (hore vpravo) mame navyše "div" - zmazať
- [x] - niekde v rámci kódu máme h1 v spane

**Nadpisy úpravy:**
Homepage

- [x] - pridať H1 do homepage - znenie "Bratislavské konto" ako sr-only 
- [x] - banner Aktualne - Nadpis kúpaliská má byť H3, nie H4
- [x] - nadpisy kariet s mestskymi sluzbami - dat ako H3

Mestské služby
- [x] - pridať H2 ako sr-only v znení "Zoznam mestských služieb"
- [x] - Nadpisy služieb v jednotlivých kartách určiť ako H3

Dane a poplatky
- [ ] - ak mam stav daň nie je k dispozícii - nadpis banneru "Vaša daň.." - H2

FaQ (Pomoc)
- [x] - Všeobecné & Daň z nehnuteľností - H3
- [x] - Nadpisy akordeónov nie sú označené - dajme ich prosím ako H4

Môj profil
- [x] - Osobné údaje, Heslo, Súhlasy - H2
- [x] - "Mám zaujem..." - H3 
- [x] - spodny link preformulovať: Prečítajte si [bližšie informácie o spracúvaní vašich osobných údajov].(https://bratislava.sk/konto/vyhlasenie-o-spracovani-osobnych-udajov).

**Comment by radoslavzeman** [comment]
> - v buttone s iniciálmi (hore vpravo) mame navyše "div" - zmazať

Toto som nenasiel, resp neviem o co presne uz ide.

> - ak mam stav daň nie je k dispozícii - nadpis banneru "Vaša daň.." - H2

Bez tohto vieme zit, nechcem to len lepit "aby bolo".
