### ISSUE TITLE
Nahradiť mocknuté Moje žiadosti requestom

### ISSUE THREAD

**Issue by radoslavzeman** [bratislava/konto.bratislava.sk#351]
Ako používateľ chcem vidieť zoznam a detail svojich odoslaných a rozpracovaných žiadostí.

https://city-account-next.staging.bratislava.sk/moje-ziadosti

`formsApi.nasesControllerGetForms`

**Comment by marykosticka** [comment]
![Image](https://github.com/bratislava/konto.bratislava.sk/assets/126803521/a532adb1-9495-4c73-a694-1e7f704c2753)

@radoslavzeman 
Pri prvých formulároch, kým je typov služieb málo sme sa s @MartinaMihalkovicova bavili, že  
- "Kategória" == Názov formuláru (napr. Záväzné stanovisko k investičnej činnosti)
- "Názov podania" == field "Názov stavby/projektu" z formulára (step Informácie o stavbe) - napr. Zwirn
- "Subcontent" v 1. fáze nemá veľmi zmysel 

Neskôr, keď bude žiadostí viac typov a prebiehala by nejaká filtrácia podľa typov žiadosti by sme to posunuli o level a 
- Kategória by bola typ kategórie (napr. Výstavba)
- Názov podania = názov žiadosti (napr. záväzko)
- Subcontent by bol názov stavby / projektu (napr. Zwirn)
