### ISSUE TITLE
Prílohy - doplniť ikonku na sťahovanie

### ISSUE THREAD

**Issue by marykosticka** [bratislava/konto.bratislava.sk#434]
Aktuálne sa po nahraní súboru zobrazí DL, čo triggerne download uploadnutého súboru - vymeniť za ikonku, ktorú si treba pýtať od Maťky

https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=5386-19529&mode=design&t=iaoYSVxHGABSyHwe-0

![Image](https://user-images.githubusercontent.com/126803521/261875551-ad24898d-fc04-422e-8dbb-8e34b29fcd71.png)

**Comment by Balros** [comment]
https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=5386-19529&mode=design&t=iaoYSVxHGABSyHwe-0
