### ISSUE TITLE
Prílohy - pridať link na info o prílohách

### ISSUE THREAD

**Issue by marykosticka** [bratislava/konto.bratislava.sk#435]
Aktuálny stav 
- step s prílohami obsahuje iba field na upload, chýba prelink na viac informácií 

Želaný stav 
- pod update fieldom bude hardcodenutý link, ktorý bude smerovať na stránku na BA webe 
-  pri záväznom stanovisku https://bratislava.sk/zivotne-prostredie-a-vystavba/rozvoj-mesta/usmernovanie-vystavby/zavazne-stanovisko-k-investicnej-cinnosti
-  pri stanovisku k investičnému zámeru https://bratislava.sk/zivotne-prostredie-a-vystavba/rozvoj-mesta/usmernovanie-vystavby/stanovisko-k-investicnemu-zameru
- viď dizajn
https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=6903-8912&mode=design&t=3p28tRMZkbDp8Wsf-4

prosím jedným vrzom rovno prelinkovať na ten istý BA web aj link v hlavičke formuláru (Viac informácií) pod názvom služby

**Comment by Balros** [comment]
Potrebuje dalsie info @mpinter. Presunute do daslieho sprintu.

**Comment by mpinter** [comment]
Link je trochu odlisny od designu. Drzime sa designov z bratislava.sk kde ikona na konci urcuje ci ostavame na rovnakej stranke (v ramci konto.bratislava.sk) alebo ci presmerovavame mimo nej

**Comment by marykosticka** [comment]
@mpinter super, vďaka, linky fungujú - ešte mi napadlo, existujú vrámci bratislava.sk kotvy na headery ? ak áno, tak by som ešte upresnila link na konkrétnu sekciu. Ak nie, tak necháme takto
