### ISSUE TITLE
SelectField refactor

### ISSUE THREAD

**Issue by radoslavzeman** [bratislava/konto.bratislava.sk#438]
For actual `SelectField`, developers didn't choose any library and implemented it manually for some reason. It causes some problems, mainly it is not accessible in many ways.
We want to replace it with new accessible components.

Some prototypes are already implemented, but they need some more work.

### What was done

Firstly, we implemented new single select an combo box (searchable select) using react-aria-component (`SelectFieldNew.tsx`, `ComboBoxNew.tsx`)
Although it is nice and accessible, react-aria doesn't support multi select.

So we tried to implement it using react-select library (`SelectMultiNew.tsx`)
Inspiration from here: https://www.jussivirtanen.fi/writing/styling-react-select-with-tailwind
Docs: https://react-select.com/home
It supports only multiselect, simple `label` options.
It does not support single select and `label` + `description` option.
It should be completely styled and accessible.

So now we have 3 components:
  - `SelectFieldNew` for single select without search
  - `ComboBoxNew` for single select with search
  - `SelectMultiNew` for multi select without search

### What needs to be done

**Important note: All prototypes could be potentially replaced by one react-select component and therefore all task below could be handled at once.**

- Crucial: it needs to support optional controlled state - [see our docs](https://bratislava.github.io/frontend/components#use-controlled-state)
- Crucial: usage in SelectFieldWidgetRJSF.tsx - controlled state and transformation of data between react-select and RJSF components
- It may need better types, see https://react-select.com/typescript
- Nicer naming :) (`SelecFieldMultiNew` 🤮)

### Useful notes for what usecases we want to support

We discussed what styles are needed in MVP with PM and designer. The outcome from the discussion is mainly about dropdowns:
- we can always use dividers
- for single select, we use only one style with check icon as indicator [figma](https://www.figma.com/file/17wbd0MDQcMW9NbXl6UPs8/DS-ESBS%2BBK%3A-Component-library?node-id=12%3A545&mode=dev)
- for multiselect, we use only checkboxes [figma](https://www.figma.com/file/17wbd0MDQcMW9NbXl6UPs8/DS-ESBS%2BBK%3A-Component-library?node-id=12%3A621&mode=dev)
- we should support simple `label` and `label`+`description` combination everywhere
- we always use dropdowns with border, we do not need shadow dropdowns
- we do not implement other styles such as radios, chevrons... they are meant for other usecases (e.g. search field on homepage)

More important requirements:
- in searchable select, we want to ignore accents (čšťôá...)
- for large selects, we need good performance and therefore virtualization #374 , some inspiration:
  - https://tanstack.com/virtual/v3
  - https://medium.com/@botsplash1/optimize-your-react-select-component-to-smoothly-render-10k-data-171760da2cad

**Comment by marykosticka** [comment]
@radoslavzeman vieš prosím testnut, ci boli implementovane poziadavky?

**Comment by mpinter** [comment]
@marykosticka ( @radoslavzeman ) ja by som to rovno zatvoril - ten cleanup v kode nastal, su tu nejake stretch-goals (virtualizacia) ale ak ich je aj viac riesil by som inde, co potrebovalo prebehnut v ramci tohto prebehlo
