### ISSUE TITLE
Komponent - Ochrana osobných údajov

### ISSUE THREAD

**Issue by marykosticka** [bratislava/konto.bratislava.sk#448]
prosím prispôsobiť tento komponent v sumári dizajnu 

https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=6626-23950&mode=design&t=iTRfIsErzqwOZOnK-4

komponent po vyjadrení právničiek nemá mať checkbox (aktuálne sa tento checkbox validuje pri odosielaní formuláru, takže treba dať pozor, či jeho odstránenie neovplyvní možnosť testovať odosielanie formuláru)

**Comment by MartinaMihalkovicova** [comment]
Uložením a/alebo odoslaním Žiadosti výslovne vyhlasujem, že som sa oboznámil s podmienkami spracúvania osobných údajov Hlavného mesta ako prevádzkovateľa osobných údajov a beriem na vedomie, že ich spracúvanie je nevyhnutné na splnenie zákonných povinností Hlavného mesta v súvislosti s riešením tejto žiadosti.

--> doplnam text od pravniciek
