### ISSUE TITLE
Alerty - upraviť na bledšie odtiene

### ISSUE THREAD

**Issue by marykosticka** [bratislava/konto.bratislava.sk#449]
Aktuálne majú alerty oveľa sýtejšie farby, prosím implementovať podľa dizajnu https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=5388-21008&mode=design&t=3p28tRMZkbDp8Wsf-4

**Comment by Balros** [comment]
Kym sme pri alertoch tak toto tiez. Odstranit `w-full` v Alert.tsx by malo pomoct


![Image](https://github.com/bratislava/konto.bratislava.sk/assets/6770524/1940ba69-b7da-498e-b451-66a5d7d0eda8)
