### ISSUE TITLE
Moje žiadosti - celá sekcia

### ISSUE THREAD

**Issue by marykosticka** [bratislava/konto.bratislava.sk#450]
Moje žiadosti majú nový look a trochu aj fungovanie. 

Sekciu treba rozedeliť na [3 taby](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20490&mode=design&t=juCVSP2vCEfsoybL-4): Odoslané, Odosiela sa, Koncepty (pribudne tým pádom tab Odosiela sa. Každá zo sekcii má určité typy stavov, ktorých významy sú popísané [tu, v časti Stavy žiadostí](https://docs.google.com/document/d/1KTvBHIzsZHHlIVpvoMNULAw4CBx-bjkg2lkkiEdVPyc/edit#heading=h.1j9s6buqkfar)

## 1. [Odoslané](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20486&mode=design&t=juCVSP2vCEfsoybL-4):
- V sekcii zobrazujeme všetky žiadosti od stavu Odoslané, t.j.: Odoslané, Doručené, Vybavuje sa, Vybavené, Zamietnuté (vizuály + ikonka sú na linku vyssie)
- po kliknutí na celý komponent alebo chevron otvoriť [Detail žiadosti](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7124-22142&mode=design&t=S8Pv9VZtdh2mxTUe-4) (dodefinujem v inom tasku)

Komponent
Vľavo:
- Typ žiadosti = zobrazíme názov žiadosti (napr. Záväzné stanovisko k investičnej činnosti)
- Text fieldu zo žiadosti = dotiahneme z konkrétneho fieldu v žiadosti, pri závazku je to field Názov stavby
- Dátum pod názvom = zobrazíme dátum, kedy bola žiadosť Odoslaná (stav Odoslané)
Vpravo:
- Stav žiadosti = ikonka + stav (farby a ikonky zobrazené vo Figme)
- Dátum, kedy sa žiadosť dostala do daného stavu

- Zobraziť max 20 žiadostí na jednu jednu stranu, následne nová strana cez pagination

[Mobile Odoslané](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20625&mode=design&t=juCVSP2vCEfsoybL-4):
- Klikateľný je celý riadok, po kliknutí zobrazíme detail žiadosti
- Zobraziť max 20 žiadostí na jednu jednu stranu, následne nová strana cez pagination
 
## 2. [Odosiela sa](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20535&mode=design&t=kQfVLv3hjoe0BqK6-4)
V sekcii Odosiela sa sú stavy Prebieha antivírová kontrola, Antivírová kontrola neúspešná, Odosiela sa, Odoslanie neúspešné. 
- Prebieha antivírová kontrola (Form state: QUEUED) - ak používateľ odošle žiadosť s neoskenovanými prílohami. Má button Zobraziť, po kliknutí zobrazí Read only (treba dopracovať) verziu danej žiadosti. Menší button s 3 bodkami obsahuje akcie [Stiahnuť ako PDF alebo Stiahnuť ako XML](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=6884-21405&mode=design&t=S8Pv9VZtdh2mxTUe-4). Žiadosť sa v tomto momente nedá vymazať. Pri kliknutí na jednotlivé akcie zobrazujeme [snackbary](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7197-9616&mode=design&t=e7PXFNBVwAoBnDz8-4)(je to už urobené pre edit mode žiadostí, možno sa dá skopírovať).
- Antivírová kontrola neúspešná (Form state: SCAN NOT SUCCESFUL) - ak bola odoslaná neoskenovaná žiadosť a pri skenovaní nájdeme v prílohách vírus. Button sa zmení zo Zobraziť na Upraviť. Po kliknutí zobrazí žiadosť na kroku Sumár a vyznačí errory v prílohách. Nedovolíme odoslať, kým nenahrá nové prílohy. Žiadosť je možné v tomto stave vymazať - 3 bodky v buttone sa zmenia na ikonku kôš. Po kliknutí zobrazíme [modal](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=5283-15031&mode=design&t=S8Pv9VZtdh2mxTUe-4) s uistením, či chce žiadosť vymazať.
- Odosiela sa (Form state: stav medzi kliknutím na ODOSLAŤ ŽIADOSŤ a DELIVERED_NASES) - prešlo antivírovou kontrolou, posiela sa do NASESu. Buttony fungujú rovnako ako pri Prebieha antivírová kontrola - nedá sa vymazať, zobrazujeme len read only
- Odoslanie neúspešné (Form state: ERROR) - ak sa náhodou stane, že sa nepodarí odoslať žiadosť do NASESu a používateľ vie s tým niečo spraviť (napr. upraviť info vo fielde, lebo sme ho mali zle nastavený). Týchto prípadov predpokladáme minimum, ale predsa sa pripravme. Fungovanie rovnako ako pri Neúspešnej antivírovej kontrole - zmeníme buttony na Upraviť + Kôš a hodíme po rozkliknutí na Sumár v žiadosti, kde budú vyznačené chybné polia.

- Po kliknutí na celý riadok sa otvorí žiadosť v mode Upraviť alebo Zobraziť, rovnako ako po kliknutí na button Upraviť / Zobraziť.
- 3 bodky (možnosti) - button s 3 bodkamib povoľuje Stiahnuť žiadosť ako XML a PDF, ak tak používateľ spraví, zobrazujeme [snackbars](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7197-9660&mode=design&t=kQfVLv3hjoe0BqK6-4) (rovnako ako v edit mode žiadostí)
- Zobraziť max 20 žiadostí na jednu jednu stranu, následne nová strana cez pagination

Komponent
Vľavo:
- Typ žiadosti (to isté ako pre Odoslané) = zobrazíme názov žiadosti (napr. Záväzné stanovisko k investičnej činnosti)
- Text fieldu zo žiadosti (to isté ako pre Odoslané) = dotiahneme z konkrétneho fieldu v žiadosti, pri závazku je to field Názov stavby
- Dátum pod názvom = zobrazíme dátum, kedy používateľ klikol na button Odoslať žiadosť 
Vpravo:
- vždy 2 buttony (primary (väčší) buď Zobraziť/Upraviť + príslušná ikonka export/oko), secondary (menší) buď 3bodky/kôš)

[Mobile Odosiela sa](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-21304&mode=design&t=kQfVLv3hjoe0BqK6-4)
- po kliknutí na konkrétnu žiadosť alebo 3 bodky sa otvárajú Akcie podľa stavu žiadosti: [Prebieha ant. kontrola](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=5283-15056&mode=design&t=4RhviBoTbRUJJMxi-4) alebo [Ant. kontrola neuspesna/Odosialnie neuspesne](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-21459&mode=design&t=4RhviBoTbRUJJMxi-4)

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/873c581f-8a17-4058-b0de-3eeb23fc4b68)

- Zobraziť max 20 žiadostí na jednu jednu stranu, následne nová strana cez pagination

## 3. [Koncepty](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20581&mode=design&t=e7PXFNBVwAoBnDz8-4)
- 3. sekcia, kde sú uložené všetky rozpracované žiadosti, ktoré si používateľ uloží ako koncept. Žiadosti majú 2 scenáre, kedy sú uložené do konceptov. Prvý, základný je, keď klikne používateľ na button Uložiť do konceptov pri vypĺňaní žiadosti a koncept sa úspešne uloží. Druhy scenár je, keď neoverený/neprihlásený user pri vypĺňaní zvolí prihlásenie/registráciu/overenie cez niektorú z výziev. Vtedy žiadosť automaticky uložíme do konceptov, aby sa k nej vedel vrátiť.
- Zobraziť max 20 konceptov na jednu jednu stranu, následne nová strana cez pagination
- [Snackbary](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7197-9696&mode=design&t=kQfVLv3hjoe0BqK6-4) pre akcie stiahnutia fungujú rovnako ako všade inde
- Všetky koncepty je možné vymazať
- Akonáhle používateľ koncept odošle, presunieme žiadosť do tabu Odosiela sa --> Odoslané a v konceptoch ju ďalej nevidí.

Komponent
Vľavo:
- Typ žiadosti = zobrazíme názov žiadosti (napr. Záväzné stanovisko k investičnej činnosti)
- Text fieldu zo žiadosti - dotiahneme z konkrétneho fieldu v žiadosti, pri závazku je to field Názov stavby. Ak používateľ uloží koncept skôr ako vyplnil tento field, dotiahneme názov zvoleného fieldu (pri záväzku by to bolo prípade "Názov stavby")
- Dátum pod názvom: zobrazíme dátum posledného uloženia do konceptov (posledná úprava). 
Vpravo:
- 2 buttony (Editovateľné koncepty - Upraviť + 3bodky, Needitovateľné koncepty Zobraziť + Kôš) - Buttony spúšťajú rovnaké akcie, ako v sekcii Odosiela sa

2 typy konceptov: 
[Editovateľné](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20593&mode=design&t=e7PXFNBVwAoBnDz8-4)
- buttony Pokračovať + [3 bodky s 3 možnosťami](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-21223&mode=design&t=e7PXFNBVwAoBnDz8-4). Po kliknutí na akcie zobrazíme buď [snackbars](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7197-9696&mode=design&t=e7PXFNBVwAoBnDz8-4) alebo [modal k vymazaniu konceptu](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7137-15506&mode=design&t=e7PXFNBVwAoBnDz8-4)

[Needitovateľné](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-21196&mode=design&t=e7PXFNBVwAoBnDz8-4)
- Ide o koncepty žiadostí, ktorým sa medzičasom zmenila schéma, a teda ich nie je ďalej možné upravovať. Button sa zmení z Pokračovať na Zobraziť a po kliknutí naň zobrazíme read only verziu formuláru. 3 bodky sa zmenia na kôš. Po kliknutí na kôš zobrazíme [modal Vymazať koncept?](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7137-15506&mode=design&t=e7PXFNBVwAoBnDz8-4).
- v prípade buttonu Zobraziť sa po hoveri zobrazí používateľovi [tooltip s vysvetlením, prečo nemôže žiadosť ďalej upravovať](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=6766-9791&mode=design&t=kQfVLv3hjoe0BqK6-4).

[Mobile Koncepty](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7124-21800&mode=design&t=kQfVLv3hjoe0BqK6-4)
- vizuálne takmer rovnaké ako Odosiela sa, akurát bez ikonky stavu
- po kliknutí na konkrétny koncept alebo 3 bodky sa otvárajú Akcie podľa stavu konceptu: [Editovateľné](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7124-21926&mode=design&t=4RhviBoTbRUJJMxi-4) alebo [Needitovateľné](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7124-22112&mode=design&t=4RhviBoTbRUJJMxi-4)
Príklad (akurát bez ikonky stavu):
![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/e35a6e69-33d8-4ddb-bea1-80146da0e34d)

- [modal pre vymazanie konceptu](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7137-15509&mode=design&t=kQfVLv3hjoe0BqK6-4)
- Zobraziť max 20 konceptov na jednu jednu stranu, následne nová strana cez pagination
- Po kliknutí na akciu Zobraziť, presmerujeme používateľa na žiadosť a zobrazíme [modal pre needitovateľné koncepty](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7124-22091&mode=design&t=kQfVLv3hjoe0BqK6-4) (rovnako ako pri desktope, modal zapracoval Marek)

**Comment by mpinter** [comment]
Preberá @Balros , zatiaľ okrem zmein vo vrchnom tab bare spísaných tu https://github.com/bratislava/konto.bratislava.sk/issues/506

**Comment by MartinaMihalkovicova** [comment]
1. [Odoslané](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20486&mode=design&t=juCVSP2vCEfsoybL-4):
* po kliknutí na celý komponent neotvára [Detail žiadosti](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7124-22142&mode=design&t=S8Pv9VZtdh2mxTUe-4) , napriek tomu, že tam je hover (otvorí sa len po kliku na chevron)
* v taboch neukazuje počty žiadostí v danom tabe, tak ako je to navrhnuté vo Figme - https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20491&mode=design&t=NWkEcCYCPtgE3J0Y-4
* dosť dlho trvá kým sa rozklikne detail žiadosti

[Mobile Odoslané](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20625&mode=design&t=juCVSP2vCEfsoybL-4): 
- sú tam navyše 3 bodky, ktoré tam nemajú byť
- klik na riadok trvá dosť dlho
- v riadku so žiadosťou medzi Názvom stavby a dátumom má byť väčeia medzera ako medzi Názvom stavby a Tyom žiadosti, viď Figma (to isté má byť aj pre Koncepty a Odosiela sa) - https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20625&mode=design&t=NWkEcCYCPtgE3J0Y-4

**Comment by MartinaMihalkovicova** [comment]
2. [Odosiela sa](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20535&mode=design&t=kQfVLv3hjoe0BqK6-4)
- Empty state - prelinkované má byť len "mestské služby" , bez slova dostupné - to dať z hyperlinku preč (to isté aj pre Odoslané  a Koncepty, aj v mobile verziách)

[Mobile Odosiela sa](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-21304&mode=design&t=kQfVLv3hjoe0BqK6-4)
- empty state je na mobile (iPhone 14pro, Safari) rozhádzaný, akoby chýbali okraje
![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/8a4efe17-532f-4e94-8e6c-248db65a8e0e)

- fungovanie stavov žiadostí musím ešte testnúť

**Comment by MartinaMihalkovicova** [comment]
3. Koncepty
Needitovateľné: 
- pridať do 3 bodiek aj možnosť Stiahnuť ako PDF
- v 3 bodkách premenovať nie Vymazať koncept, ale iba Vymazať
- po kliknutí na Vymazať koncept máme rozhádzaný modal, správne vyzerá takto: https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7137-15506&mode=design&t=NWkEcCYCPtgE3J0Y-4

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/b89724ce-162b-4286-832f-b2df7d9f1285)


Mobile Koncepty: 
- akcie po kliku na 3 bodky majú široké riadky, má to vyzerať takto: https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7164-16037&mode=design&t=NWkEcCYCPtgE3J0Y-4 

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/bcb98b69-1c42-4a21-9f09-ceb9643df0ea)

- pridať možnosť PDF ako desktop
- Vymalzať koncept -> Vymazať
- rozhádzaný Vymazať modal

**Comment by Balros** [comment]
> 1. [Odoslané](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20486&mode=design&t=juCVSP2vCEfsoybL-4):
> 
> * po kliknutí na celý komponent neotvára [Detail žiadosti](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7124-22142&mode=design&t=S8Pv9VZtdh2mxTUe-4) , napriek tomu, že tam je hover (otvorí sa len po kliku na chevron)
> * v taboch neukazuje počty žiadostí v danom tabe, tak ako je to navrhnuté vo Figme - https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20491&mode=design&t=NWkEcCYCPtgE3J0Y-4
> * dosť dlho trvá kým sa rozklikne detail žiadosti
> 
> [Mobile Odoslané](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20625&mode=design&t=juCVSP2vCEfsoybL-4): 
> 
> * sú tam navyše 3 bodky, ktoré tam nemajú byť
> * klik na riadok trvá dosť dlho
> * v riadku so žiadosťou medzi Názvom stavby a dátumom má byť väčeia medzera ako medzi Názvom stavby a Tyom žiadosti, viď Figma (to isté má byť aj pre Koncepty a Odosiela sa) - https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20625&mode=design&t=NWkEcCYCPtgE3J0Y-4

- po kliknutí na celý komponent neotvára -> otvara len to treba vyckat -> mozne riesenia:
  - da sa to riesit najprv zrychlenim otvarania (to neviem co obnasa z FE strany)
  - tiez by sme mohli usera rovno presmerovat a zobrazit mu radsej nejaky skeleton ako ho nechat cakat na povodnej stranke bez ziadnej indikacie nacitavania - pobavme sa o tom
- v taboch neukazuje počty žiadostí -> [tento task](https://github.com/bratislava/konto.bratislava.sk/issues/506)
- to tretie je v priamom rozpore s prvym bodom

**Comment by Balros** [comment]
> 2. [Odosiela sa](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20535&mode=design&t=kQfVLv3hjoe0BqK6-4)
> 
> * Empty state - prelinkované má byť len "mestské služby" , bez slova dostupné - to dať z hyperlinku preč (to isté aj pre Odoslané  a Koncepty, aj v mobile verziách)
> 
> [Mobile Odosiela sa](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-21304&mode=design&t=kQfVLv3hjoe0BqK6-4)
> 
> * empty state je na mobile (iPhone 14pro, Safari) rozhádzaný, akoby chýbali okraje
>   ![Image](https://user-images.githubusercontent.com/132052087/277334258-8a4efe17-532f-4e94-8e6c-248db65a8e0e.PNG)
> * fungovanie stavov žiadostí musím ešte testnúť

- Empty state - prelinkované... -> fixed
- empty state je na mobile... -> fixed
- fungovanie stavov žiadostí musím ešte testnúť -> ok

**Comment by Balros** [comment]
> 3. Koncepty
> 
> * nedoťahuje názov stavby/projektu
> 
> Editovateľné:
> 
> * button má byť Pokračovať, nie Upraviť - [Figma](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7120-20593&mode=design&t=NWkEcCYCPtgE3J0Y-4)
> * v 3 bodkách premenovať z Vymazať koncept iba na Vymazať
> * chýba orámovanie 3 bodiek:
> 
> ![Image](https://user-images.githubusercontent.com/132052087/277341840-b1eda1d7-e55f-4c0e-8623-ba1fcc22f163.png)
> 
> Needitovateľné:
> 
> * pridať do 3 bodiek aj možnosť Stiahnuť ako PDF
> * v 3 bodkách premenovať z Vymazať koncept iba na Vymazať
> * po kliknutí na Vymazať koncept máme rozhádzaný modal, správne vyzerá takto: https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7137-15506&mode=design&t=NWkEcCYCPtgE3J0Y-4
> 
> ![Image](https://user-images.githubusercontent.com/132052087/277339575-b89724ce-162b-4286-832f-b2df7d9f1285.png)
> 
> Mobile Koncepty:
> 
> * akcie po kliku na 3 bodky majú široké riadky, má to vyzerať takto: https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7164-16037&mode=design&t=NWkEcCYCPtgE3J0Y-4
> 
> ![Image](https://user-images.githubusercontent.com/132052087/277340513-bcb98b69-1c42-4a21-9f09-ceb9643df0ea.PNG)
> 
> * pridať možnosť PDF ako desktop
> * Vymalzať koncept -> Vymazať
> * rozhádzaný Vymazať modal

- nedoťahuje názov stavby/projektu -> myslim ze to je fixnute, ak sa to este stale deje prosim urobme z toho novy task
- button má byť Pokračovať... -> fixed
- chýba orámovanie 3 bodiek -> fixed

- pridať do 3 bodiek aj možnosť Stiahnuť ako PDF -> 
- v 3 bodkách premenovať z Vymazať koncept iba na Vymazať -> fixed
- po kliknutí na Vymazať koncept máme rozhádzaný modal -> fixed

**Comment by marykosticka** [comment]
potvrdzujem, že je fixed a zatvaram
