### ISSUE TITLE
Bug - Snackbary timing

### ISSUE THREAD

**Issue by MarekBodingerBA** [bratislava/konto.bratislava.sk#461]
Snackbar ostane v stave "Koncept sa ukladá." Pričom sa už uložil. Treba spraviť lepší snackbar management.

https://github.com/bratislava/konto.bratislava.sk/assets/104828482/6f76be49-b28d-47be-85d4-f4d063a566b8

**Comment by MartinaMihalkovicova** [comment]
momentálne nefunguje ukladanie konceptov vobec

**Comment by MarekBodingerBA** [comment]
> momentálne nefunguje ukladanie konceptov vobec

Prosím viac info.

**Comment by mpinter** [comment]
Bigger fish to fry - toto zatváram, rewrite snackbarov odkladáme.
