### ISSUE TITLE
FE - posielanie cez EID iba keď nases/can-send/:id vráti true

### ISSUE THREAD

**Issue by erehulka** [bratislava/konto.bratislava.sk#474]
Keďže chceme formuláre cez EID posielať bez queue (kvôli expirácii tokenu), tak treba povoliť posielanie iba keď `nases/can-send/:id` vráti `canSend = true`.

**Comment by mpinter** [comment]
@erehulka chcem si overit - pozrel som na kod toho endpointu a okrem neocakavanych chyb vyzera ze ti to nema dovolit odoslat iba ak este prebieha scanovanie

ak je to tak, tak toto uz sa dnes na FE deje aj ked to nepouziva tento endpoint (ale kontroluje ci z priradenych priloh je nejaka este scanovana). Mozme v tom pripade nechat ako je ? Logika by mala byt zachovana. Daj vediet ci sa tu kontroluje este nieco ine co mi uchadza.
