### ISSUE TITLE
Schémy ZST a SIZ majú rovnaký názov

### ISSUE THREAD

**Issue by marykosticka** [bratislava/konto.bratislava.sk#475]
Schémy https://city-account-next.staging.bratislava.sk/mestske-sluzby/zavazne-stanovisko-k-investicnej-cinnosti a https://city-account-next.staging.bratislava.sk/mestske-sluzby/stanovisko-k-investicnemu-zameru sa obe volajú Záväzné stanovisko k investičnej činnosti -> prosím premenovať druhú na Stanovisko k investičnému zámeru

**Comment by erehulka** [comment]
Toto bude vec asi skôr pre frontend: https://github.com/bratislava/konto.bratislava.sk/blob/16b1d6ee42e58820d755b4c8c265170f7e8ca288/next/components/forms/simple-components/FormHeader.tsx#L39

je to tam hardcoded na záväzné stanovisko
