### ISSUE TITLE
updatenuť info na webe k daným službám

### ISSUE THREAD

**Issue by marykosticka** [bratislava/konto.bratislava.sk#508]
MVP je zameniť linky, ktoré odkazujú na elektronickú žiadosť za linky, ktoré budú smerovať na formulár v Bratislavskom konte na stránkach 

https://bratislava.sk/zivotne-prostredie-a-vystavba/rozvoj-mesta/usmernovanie-vystavby/zavazne-stanovisko-k-investicnej-cinnosti
https://bratislava.sk/zivotne-prostredie-a-vystavba/rozvoj-mesta/usmernovanie-vystavby/stanovisko-k-investicnemu-zameru

**Comment by marykosticka** [comment]
dohodnuté, že zmenia až po sviatkoch, keďže teraz nemáme kapacity, ktoré by riešili prípadný support

**Comment by MartinaMihalkovicova** [comment]
@marykosticka tu sa niečo pohlo prosím?
