### ISSUE TITLE
Bugy z testovania formulárov

### ISSUE THREAD

**Issue by Balros** [bratislava/konto.bratislava.sk#511]
REGISTRÁCIA/PRIHLÁSENIE/OVERENIE z modalov 
- akonáhle sa prihlásim/registrujem a predpokladám, že aj overím (ale overenie som nevedela testnúť) cez klik na nejaký button v modaly/headeri, nevráti ma späť na formulár tam, kde som bola naposledy. Presmeruje ma na HP, mala by som sa dostať na formulár tam, na krok, kde som sa nachádzala naposledy.

**Comment by MartinaMihalkovicova** [comment]
hodilo ma sice na prvy krok formularu, nie na sumar, odkial som isla, ale v prvej faze mozeme nechat tak

**Comment by marykosticka** [comment]
@MartinaMihalkovicova môžeme dať teda ako done?

**Comment by MartinaMihalkovicova** [comment]
prehodila som ako done
