### ISSUE TITLE
Modal "Žiadosť je možné odoslať cez Bratislavské konto alebo pomocou eID" visual issues

### ISSUE THREAD

**Issue by mpinter** [bratislava/konto.bratislava.sk#522]
Stale nie je podla figmy: https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?node-id=6558%3A27661&mode=dev

Desktop dnes:

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/2327312/7b64a065-bf10-4e8a-882d-f145934dd8c3)

Mobil dnes:

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/2327312/58c464f7-119d-4348-8b5d-2c719789c27c)

Najvacsie rozdiely v mobilnej verzii. V desktop verzii nesedia niektore fonty (velkost / weight, minimalne pri nadpise a linku "prihlasit sa", dalej som nepozeral).

Ak su toto kompromisy ktore boli dohodnute tak staci dat vediet / odkazat sa / doplnit do komentarov. V tom pripade by som ale riesil s Patrikom ze minimalne desktop verzia nevyzera prilis dobre.

**Comment by MartinaMihalkovicova** [comment]
prosim, tohto sa niekto chytal? Lebo je to v to test, ale mobil vyzera stale uplne inak ako ma vyzerat a je to na prvu viditelne, ze to tak nema byt :)

**Comment by MartinaMihalkovicova** [comment]
- všetky modaly na mobile sú orámované modrou (Safari, iPhone 14pro)

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/7c34970a-60aa-49b5-aae3-2b01797df759)
![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/5598531b-9cc0-463c-b648-64f6d96e873e)
![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/8f680e62-5eab-43b7-bcd6-2688445b1b72)


- po kliknutí na button Vytvoriť BA konto alebo Prihlásiť sa mi hodí snackbar o ukladaní konceptu a presmerovávaní

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/93d2a52f-8659-45a4-bb32-f8579eac142c)

ostatne super :)
