### ISSUE TITLE
Modal "vymazat koncept" - zle/chybajuce texty

### ISSUE THREAD

**Issue by mpinter** [bratislava/konto.bratislava.sk#539]
![Image](https://github.com/bratislava/konto.bratislava.sk/assets/2327312/e3ec4fdf-7860-4338-bf97-adb1dc81b6e0)

**Comment by MartinaMihalkovicova** [comment]
- button Vymazať tu má byť červený
- inak sú tu tiež tie chyby rovnaké ako pri ostatných modaloch:

buttony v modaloch sú veľké, mali by byť “small”
button Späť v modaly má byť akoby boldom
veľa textov je posunutých a nadpisy nie sú vycentrované

**Comment by Balros** [comment]
- farba buttonu zmenena na cervenu
- button spat je boldom ale zvolil som standardnu velkost 16 px, nie 14 px ako je vo figme

**Comment by Balros** [comment]
- button Vymazat zmneny na cervenu farbu
- button spat zmeneny na akoby bold (velkost pisma je standarnych 16px nie 14px ako vo figme)
- ostatne problemy budu sucastou globalneho riesenia modalov

**Comment by MartinaMihalkovicova** [comment]
Po zmazaní konceptu mi hodilo snackbar PDF bolo stiahnuté: 

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/499dd07e-9f9e-4a3c-b829-c1a102e6e388)

**Comment by MartinaMihalkovicova** [comment]
Prosím, držme sa v textácii figmy: https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7780-21563&mode=design&t=8DX0cQwlbL8aF2nz-4 

Nie Koncept zmazaný ako to je teraz, ale "Koncept bol vymazaný.". To isté aj pre ostatné typy snackbarov (Koncept sa maže., Koncept sa nepodarilo vymazať.)
