### ISSUE TITLE
[Moje ziadosti] Chyba pri odosielani suborov na GINIS nema presunut formular do tabu odosiela sa

### ISSUE THREAD

**Issue by mpinter** [bratislava/konto.bratislava.sk#544]
Nie kazdy error znamena stlpec "odosiela sa", dnes vsak logika pravdepodobne vyzera takto. Je treba rozoznavat errors, pri tych ktore nastanu po tom co uspesne prebehne odosielanie na ginis iba informovat v poslednom stlpci.

**Comment by mpinter** [comment]
suvisi s https://github.com/bratislava/konto.bratislava.sk/issues/554

**Comment by Balros** [comment]
cakam na vyjadrenie od @lukaspolesnak ci by davalo zmysel spravit dva errorove stavy (state) formularov:

ERROR_SYSTEM
ERROR_USER
namiesto jedneho:

ERROR

**Comment by Balros** [comment]
Caka na https://github.com/bratislava/konto.bratislava.sk/issues/662

**Comment by mpinter** [comment]
Zatvaram, asi nie je viac relevantne - ked tak by bolo treba zamysliet sa nad sekciou moje ziadosti
