### ISSUE TITLE
Novy stav formularu SENDING_TO_NASES

### ISSUE THREAD

**Issue by Balros** [bratislava/konto.bratislava.sk#547]
Zapracovanie SENDING_TO_NASES, ktorý formulár dosiahne tesne pred tým, ako sa naozaj odošle na NASES ([task](https://github.com/orgs/bratislava/projects/6/views/5?pane=issue&itemId=41884029)). https://github.com/bratislava/nest-forms-backend/pull/199

**Comment by marykosticka** [comment]
@Balros kto a ako vie otestovať?

**Comment by MartinaMihalkovicova** [comment]
@Balros
