### ISSUE TITLE
pri nahratí z XML sa nenahrajú údaje

### ISSUE THREAD

**Issue by mpinter** [bratislava/konto.bratislava.sk#576]
Keď nahrám vyplnené XML, údaje sa nenahrajú do formulára - niektoré stepy sa síce označia ako vyplnené, ale ide o stepy, kde je iba radiobutton, ktorý je defaultne vyplnený. Vybehne snackbar, že XML bolo nahraté a v Console tiež nevyhodí žiaden error. 

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/126803521/7ece5357-6fed-48f1-920b-8ccab630a61b)

**Comment by marykosticka** [comment]
@mpinter stále nefunguje, XML, ktoré som skúšala ti pošlem do správy, skús pls aj u seba

**Comment by mpinter** [comment]
@marykosticka po doplneni na slacku (papertrail for future gen: co na tomto bolo pokazene bolo generovanie xml, pre vsetky "stare" xml to nepojde, pre novo vygenerovane uz by malo byt vsetko v poriadku), je toto doriesene ?
