### ISSUE TITLE
[Text] Bug: snackbar navyše

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#590]
- po kliknutí na button Vytvoriť BA konto alebo Prihlásiť sa mi hodí snackbar o ukladaní konceptu a presmerovávaní. Tuto vôbec nemá byť snackbar, ak niečo, tak spinner v buttone

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/93d2a52f-8659-45a4-bb32-f8579eac142c)

**Comment by Balros** [comment]
Dohodnute s @MartinaMihalkovicova ze snackbar zostane ale zmeni sa text.

**Comment by Balros** [comment]
@MartinaMihalkovicova stale cakam na text
