### ISSUE TITLE
Bug: nefunkčný button Overiť identitu v hlavičke pri formulároch

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#595]
Ak som prihlásený ale neoverený používateľ a dostanem sa na vypĺňanie formuláru, nefunguje button Overiť identitu v hlavičke. Správa sa ako klikateľný, ale po kliknutí naň nereguje, ostane v stave clicked, ale nič nerobí. 

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/5b35fc18-c853-4e86-8819-c2338db93917)
![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/0f38c86c-87b9-44b0-b922-09f39bd31b48)

**Comment by marykosticka** [comment]
@MartinaMihalkovicova mne to funguje normálne, ale skús prosím aj ty, keďže u teba to haprovalo, dakujem!
