### ISSUE TITLE
upgrade 'aws-amplify' na v6

### ISSUE THREAD

**Issue by Balros** [bratislava/konto.bratislava.sk#604]

**Comment by MarekBodingerBA** [comment]
Ahojte, upgradol sa Amplify na novú verziu, v podstate všetko súvisiace s autentifikáciou sa technicky zmenilo, takže som to musel premigrovať na nové verzie, čo by si zaslúžilo odtestovať:
- registrácia
- prihlásenie
- registrácia, preskočiť overenie cez email a potom sa skúsiť prihlásiť a overiť email na prihlasovacej stránke
- odhlásenie
- odhlásenie cez /odhlasenie
- zmena emailu
- zmena kontaktných údajov
- zmena hesla
- zabudnuté heslo
