### ISSUE TITLE
Bug: aj po odoslaní zobrazujeme podanie v tabe odosiela sa

### ISSUE THREAD

**Issue by marykosticka** [bratislava/konto.bratislava.sk#608]
Po odoslaní podania s naskenovanými prílohami sa podanie hneď zobrazilo v tabe Odoslané, ale zároveň aj v tabe Odosiela sa zobrazujeme, že by tam malo byť 1 podanie. Po kliknutí na tab je ale prázdny (viď gif)

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/126803521/2e88d4d8-cd8e-4447-a1b1-4c15ed3d6c91)

**Comment by marykosticka** [comment]
s @Balros sme zistili, že skutočný problém tkvie v tom, že tab odoslané / odosiela sa / koncepty sa automaticky nerefreshuje, čísla v zátvorkách sa upravia až po manuálnom refreshi

**Comment by Balros** [comment]
Vyriesene ciastocne. Uplne riesenie po spraveni tohto tasku https://github.com/bratislava/konto.bratislava.sk/issues/670

**Comment by MartinaMihalkovicova** [comment]
testla som a ziadosti mam sice v Odosiela sa, ale cislo tam mam 0

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/3200b834-d0ea-4262-95ec-4e35adbc95de)

**Comment by MartinaMihalkovicova** [comment]
Prave mi to preslo do Odoslane a aj tam mam 0


![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/8b480026-557c-4d0d-827e-22c429f23219)



Takisto koncepty, ukazuje mi 1, napriek otmu, ze ich tam mam ovela viac


![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/fe9e3a38-6ee3-4b4c-afdb-7146d088be4f)
