### ISSUE TITLE
chybajuci nazov prihlasenej entity v hlavicke (pravnicka osoba)

### ISSUE THREAD

**Issue by Balros** [bratislava/konto.bratislava.sk#612]
![image](https://github.com/bratislava/konto.bratislava.sk/assets/6770524/3b702ae5-689a-44d0-984d-bd40c86f0577)

**Comment by marykosticka** [comment]
@Balros toto už môžeme uzavrieť? vidím to releasnute na produkcii

**Comment by Balros** [comment]
ano
