### ISSUE TITLE
Vytvorit strapi pre konto

### ISSUE THREAD

**Issue by Balros** [bratislava/konto.bratislava.sk#614]
Preco by sa hodilo strapi:

- obsluha kachliciek v mestskych sluzbach
- obsluha horneho alertu
- obluha AnnouncmentBlock
- obsluha bannerov?

**Comment by MarekBodingerBA** [comment]
general-strapi nestačí?
https://general-strapi.bratislava.sk/admin/

**Comment by Balros** [comment]
Caka na https://github.com/bratislava/konto.bratislava.sk/pull/813

**Comment by MartinaMihalkovicova** [comment]
preklápam obsah, na ktorom sme sa dohodli, že by mal v kontovom Strapi v prvej fáze byť:
**alerty**
![image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/aeff358f-4504-4f69-9579-c7fc8f9de883)

**dlaždice v mestských službách**
- farba
- badge (jeho verzie)
- ikonky
- text
![image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/e2542831-51af-497b-8786-f0e7f82eee70)

**FAQs** (tu chceme najprv ale spravit kategorizaciu do vacsich celkov, cakam na Patrikov navrh)
- ich kategorizácia
- text v akordeonoch
- headline
![image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/a7441a06-05f2-4b82-b52f-8e4480fac889)

**bannery v časti aktuálne na HP**
- image
- headline
- text
- button (volitelny)
- text buttonu
- right/left verzia
![image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/70a4e967-3f59-441f-b2c1-9fb0da82c09d)

**možnosť zvoliť 4 dlaždice na HP**
- blank screens (napr. dane)
- image
- headline
- text
- left/right
![image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/9a63db21-5615-404a-8596-dd868f8e4d8e)

**blank screens (napr. dane)**
- image
- headline
- text
- left/right 
![image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/ebacb34e-bae6-48d8-8ac0-b7f87293e9e1)

Na prejdenie si s Patrikom ostávajú LP jednotlivých formulárov. Až budeme mať vydefinované ako presne sa majú úpužívať, vieme to nastaviť aj v Strapi.

Do úzadia sme odložili tvorbu a skladanie formulárov cez Strapi, ktoré by umožnilo produkťákom vytvárať formuláre bez väčšej pomoci dev, kvôli komplikovanosti riešenia.

**Comment by MarekBodingerBA** [comment]
Vyberám z Done, spravilo sa len Strapi, ale content treba ešte preklopiť.
