### ISSUE TITLE
Client-side error pri registrácii (staging)

### ISSUE THREAD

**Issue by marykosticka** [bratislava/konto.bratislava.sk#618]
po kliknutí na Registovať v ďalšom stepe zobrazí toto (bez ohľadu na to, či je to FO, PO, FO-p)

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/126803521/38cb8049-206f-404d-909e-75353ada8062)

**Comment by Balros** [comment]
to bola ta chyba z lambdou na Cognite, neviem v akom to je stave

**Comment by mpinter** [comment]
Error ktory to triggeroval odstraneny, ale issue nechavame - problem je aj to ze ked sa vyskytne necakana chyba dostaneme error 500 namiesto niecoho krajsieho.

**Comment by mpinter** [comment]
Ok, on second thought, toto zatvarame , otvorime novy issue na error zo screenshota.
