### ISSUE TITLE
Formuláre predzáhradky / komunitné záhrady

### ISSUE THREAD

**Issue by mpinter** [bratislava/konto.bratislava.sk#625]
Preklopiť tieto formuláre medzi kontové.

https://bratislavskisusedia.sk/temy/predzahradky#Formul%C3%A1r

https://bratislavskisusedia.sk/temy/komunitne-zahrady#Registr%C3%A1cia

Použiť existujúce funkcie generujúce polia - ak by niečo chýbalo radšej prispôsobiť formulár. Inšpirovať sa dá daňovým formulárom, testovať tiež rovnakým spôsobom.

Čokoľvek čo bude v tomto procese nejasné doplniť do dokumentácie (napríklad do README v schema-generator directory).

**Comment by MarekBodingerBA** [comment]
Asi bude chýbať ten mapový komponent, či?

**Comment by MarekBodingerBA** [comment]
A ešte by som pozrel ako sú spravnené mená + adresy v iných formulároch (kontových) nech to je konzistentné.

**Comment by mpinter** [comment]
@MarekBodingerBA mapovy komponent - ano, sme dohodnuty ze zatial bez neho, mena adresy good point

**Comment by mpinter** [comment]
@jitka1997 od @KuboHBA sme dostali este designy k tymto formularom z roku pana 🙂 fieldy by mali byt rovnake ako v tom co je dnes na webe ale zaroven tu existovalo rozdelenie do krokov. Toto by sme mohli rovno spravit aj my, ak to nie je privela extra prace (verim ze by nemuselo byt).

Designy tu:
Predzáhradky - https://www.figma.com/file/6JfDMMDUUVjuYjVZZw4zMZ/Elektronick%C3%A9-slu%C5%BEby-(old-design)?type=design&node-id=385-13603&mode=design

Komunitné záhrady - https://www.figma.com/file/6JfDMMDUUVjuYjVZZw4zMZ/Elektronick%C3%A9-slu%C5%BEby-(old-design)?type=design&node-id=385-13604&mode=design
