### ISSUE TITLE
PDF - zmena názvu

### ISSUE THREAD

**Issue by marykosticka** [bratislava/konto.bratislava.sk#632]
v PDF prosím zmeniť názov 
- zo "Záväzné stanovisko k investičnej činnosti" na "Žiadosť o záväzné stanovisko k investičnej činnosti"
- zo "Stanovisko k investičnému zámeru" na "Žiadosť o stanovisko k investičnému zámeru"

**Comment by MartinaMihalkovicova** [comment]
Upravené, len nechceme zmeniť aj názov súboru? Zatiaľ je zmenený len názov priamo v žiadosti (headline)

@marykosticka

**Comment by MartinaMihalkovicova** [comment]
@marykosticka

**Comment by marykosticka** [comment]
@MartinaMihalkovicova názvy súborov sú vedené ako samostatný task, tento teda zatváram :)
