### ISSUE TITLE
PDF - zobrazovať miesto ID príloh názvy súborov

### ISSUE THREAD

**Issue by marykosticka** [bratislava/konto.bratislava.sk#633]
vieme prosím miesto ID príloh zobrazovať v PDF názvy súborov? referenti by si podľa toho vedeli kontrolovať s Ginisom, či majú naozaj všetky prílohy a ak nie, tak ktorá konkrétne neprešla

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/126803521/64156f28-60bf-4e91-89c0-af3b061cb950)

**Comment by mpinter** [comment]
@marykosticka ak koli daniam budeme posuvat url suborov do minia, tak by sme to teoreticky mohli spravit aj tu a tym padom ich mat citatelne. Bonus points ak to nechame otvorene a pouzivatel si pri odoslanych podaniach bdue vediet tymto sposobom pozriet subory ktore odoslal

**Comment by marykosticka** [comment]
@MarekBodingerBA kedze Pinto je na dovolenke, nevies mi poradit, ako toto riesite na daniach, nech viem, ci sa to bude dat eventualne prepouzit?

**Comment by marykosticka** [comment]
@MarekBodingerBA ping :)

**Comment by MarekBodingerBA** [comment]
na daniach sa generuje custom PDFko - takže to nesúvisí nijak

**Comment by marykosticka** [comment]
@mpinter toto by sa malo vyriešiť novým PDFkom nie? tým pádom asi môžeme zavrieť
