### ISSUE TITLE
PDF / GINIS - doplniť dátum reálneho odoslania žiadosti

### ISSUE THREAD

**Issue by marykosticka** [bratislava/konto.bratislava.sk#634]
referenti potrebujú vedieť dátum, kedy bola žiadosť odoslaná cez konto, aby si od nej počítali lehoty. Vieme to doplniť niekde do PDFka, alebo ešte lepšie do Ginisu?

**Comment by mpinter** [comment]
@marykosticka tu sa chceme dohodnut ktory je pre nas zavazny datum (odoslanie alebo dotecenie do NASESu)?

**Comment by marykosticka** [comment]
@mpinter Potvrdenie o  odoslaní v zmysle [§ 25 ods. 1](https://www.slov-lex.sk/pravne-predpisy/SK/ZZ/2013/305/20180401#paragraf-25.odsek-1) zákona o e-Governmente má význam najmä z pohľadu počítania a zachovávania procesnoprávnych lehôt. **Elektronické podanie je podané jeho odoslaním do elektronickej schránky orgánu verejnej moci.** Na účely preukázania momentu odoslania sa použijú údaje z potvrdenia podľa [§ 5 ods. 8](https://www.slov-lex.sk/pravne-predpisy/SK/ZZ/2013/305/20180401#paragraf-5.odsek-8) zákona o e-Governmente.

**Comment by mpinter** [comment]
@marykosticka ak je GINIS idealne miesto tak toto je dnesny stav - aj ked sa nam dnes vie zaseknut "klikacka", tak datum stihanutia do GINISu je datum dorucenia do schranky +-40minut (mozeme sa rozpravat o edgecaseoch ale to sa potom mozeme rozpravat pri vsetkej elektronickej komunikacii mesta). Je to vidno aj vo fielde "Podane", aj sa podla toho vyzera ze nastavuje "Termin vybavenia" (screenshot z nejakeho dlho zaseknuteho podania, 🤞 ze testovacieho.

Daj vediet ci to tym padom treba dalej riesit.



![Image](https://github.com/bratislava/konto.bratislava.sk/assets/2327312/5ebe71eb-46d9-4fcd-97da-521f8171cefa)
