### ISSUE TITLE
PDF - prehádzané poradie fieldov

### ISSUE THREAD

**Issue by marykosticka** [bratislava/konto.bratislava.sk#636]
PDF nezobrazuje fieldy v rovnakom poradí, ako sú vo formulári - ideálne by to malo presne reflektovať poradie

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/126803521/6188ff36-b7c4-4903-ab94-6ace4b22daee)

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/126803521/df23bd4e-8646-4f5b-85cf-5ea5b1026530)

**Comment by MarekBodingerBA** [comment]
Nemyslím si, že toto pôjde spraviť - to v akom poradí sú fieldy je v UI scheme, čo ide úplne mimo tohto PDF generátoru.

**Comment by marykosticka** [comment]
@mpinter @MarekBodingerBA toto by sa malo vyriešiť novým PDFkom nie? tým pádom asi môžeme zavrieť

**Comment by MarekBodingerBA** [comment]
> @mpinter @MarekBodingerBA toto by sa malo vyriešiť novým PDFkom nie? tým pádom asi môžeme zavrieť

true dat
