### ISSUE TITLE
Bug - dlhé názvy súborov na mobile

### ISSUE THREAD

**Issue by MarekBodingerBA** [bratislava/konto.bratislava.sk#643]
Dlhy string v nazve suboru sa ma zalamovat aj ak je to iba jedno slovo.

**Comment by MarekBodingerBA** [comment]
![Image](https://github.com/bratislava/konto.bratislava.sk/assets/104828482/3f7aab82-e1ba-4dc8-8e05-17e3a97ea17c)

**Comment by daksas303** [comment]
It was already fixed.
