### ISSUE TITLE
[Moje ziadosti] Oddelit specialny druh BE erroru ktory vie user opravit

### ISSUE THREAD

**Issue by Balros** [bratislava/konto.bratislava.sk#662]

**Comment by marykosticka** [comment]
@lukaspolesnak @erehulka prosím, ešte stále je na review?

**Comment by Balros** [comment]
pravdepodobne tento nedokonceny PR https://github.com/bratislava/nest-forms-backend/pull/252 s tym suvisi

**Comment by erehulka** [comment]
@Balros toto je done, PR bol mergnutý
