### ISSUE TITLE
Presmerovania pre neprihlasenych pouzivatelov server-side

### ISSUE THREAD

**Issue by mpinter** [bratislava/konto.bratislava.sk#664]
Dnes, pokial podstranka vyzaduje prihlasenie, sa najskor nacita client-side, "preblikne", a potom presmeruje pouzivatela na prihlasenie. Hlavny dovod preco sa toto deje client side je pritom to, ze sme povodne nemali informaciu o prihlaseni/odhlaseni a j v cookie na backende. Dnes ked ju mame, mali by sme tieto redirecty robit z getServerSideProps

Treba dat pozor aby nadalej fungovala feature, kedy po presmerovani ostava v query parametry cesta odkial clovek prisiel, a po prihlaseni je clovek vrateny na tuto cestu.

Poznamka pod ciarou: okrem tohto druhu presmerovavania sa nachadza v appke aj presmerovavanie na slovensko.sk prihlasenie, toho sa tato uloha netyka.

**Comment by MarekBodingerBA** [comment]
https://github.com/bratislava/konto.bratislava.sk/pull/661
Ja už som to adresoval tu, tak neviem či tu nemôže nastať nejaký konflikt.

**Comment by mpinter** [comment]
Je to tak, tym padom to je duplikat, zatvaram.
