### ISSUE TITLE
BE - najst sposob ako sa jednoducho dostat k celkovym poctom ziadosti v requeste '/nases/forms'

### ISSUE THREAD

**Issue by Balros** [bratislava/konto.bratislava.sk#670]

**Comment by mpinter** [comment]
Na tomto uz spravila BE pracu @jitka1997 , treba sa potom syncnut a doklepnut.

**Comment by Balros** [comment]
Duplicita https://github.com/bratislava/nest-forms-backend/issues/255, zatvaram tento task nechavam iba ten druhy.
