### ISSUE TITLE
[Text] Uprava textu fieldu tel. č.

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#673]
Prosím, upravme fieldy s telefónnym číslom vo formulároch aj v profile tak, aby tam bol placeholder ako je to teraz spravené v susedských formoch:

Teraz: 
![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/5e6f912a-1af7-48e7-bd19-0fffa74bdef7)

Želaný stav: 

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/6f32634e-ddcd-4b52-88ec-08ec22ffc7af)

**Comment by MartinaMihalkovicova** [comment]
@jitka1997 upravila som znenie tasku tak, aby to davalo zmysel

**Comment by mpinter** [comment]
tyka sa zdielanych fieldov medzi formularmi

**Comment by MartinaMihalkovicova** [comment]
V žiadosti o závzné stanovisko k investičnej činnosti, stanovisko k investičnému zámeru ani v mojom profile túto zmenu na stagingu nevidím. @jitka1997

**Comment by MartinaMihalkovicova** [comment]
V žiadostiach je to upravené, ale ešte prosím dorobme úpravu v časti Môj profil: https://city-account-next.staging.bratislava.sk/moj-profil, po kliknutí na Upraviť údaje


![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/b2cc1ae6-a31d-4370-81fd-0d20470315c6)

**Comment by jitka1997** [comment]
> @jitka1997 Super, vďaka, v žiadostiach je to upravené, ale ešte prosím dorobme úpravu v časti Môj profil: https://city-account-next.staging.bratislava.sk/moj-profil, po kliknutí na Upraviť údaje
> 
> ![Image](https://private-user-images.githubusercontent.com/132052087/317191706-b2cc1ae6-a31d-4370-81fd-0d20470315c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTIwMTAsIm5iZiI6MTcxMTcxMTcxMCwicGF0aCI6Ii8xMzIwNTIwODcvMzE3MTkxNzA2LWIyY2MxYWU2LWEzMWQtNDM3MC04MWZkLTBkMjA0NzAzMTVjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQxMTI4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjFjMGNkZDYwNDA0MDExNWU4YTVhZGU3YTAxODhmNTllNzdmYzI0ZGZlNGM3MDRjZTkyOGU5YzhkNzc0YmI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Io9glgiZZvsQSNpMev6WX466bymJdzoaeii9IKcs4Ts)
> 
> Mimo upravovacieho režimu sa bude field volať len Telefónne číslo, zmizne odtiľ zátvorka, ktorá je tam teraz
> 
> ![Image](https://private-user-images.githubusercontent.com/132052087/317192036-96c3c1c6-6982-41ad-acbd-f9ceed758dce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTIwMTAsIm5iZiI6MTcxMTcxMTcxMCwicGF0aCI6Ii8xMzIwNTIwODcvMzE3MTkyMDM2LTk2YzNjMWM2LTY5ODItNDFhZC1hY2JkLWY5Y2VlZDc1OGRjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQxMTI4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmJkNmI2ZWRiN2MxZGYxOWEzYTQzYjhlM2IxYWU3OWY5NTIyZjQ0NzM1ZmJhY2NjMzRiZTkwNzllNmI1MTRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QNCbmTVS9tYDsrY7ac4IX_OJaVgEK1IAd6rFTIsGRwU)

@MartinaMihalkovicova  Upravene, este som nasla jedno miesto, kde je tento field po starom, po registracii v modali pre doplnenie telefonneho cisla. Upravila som tiez, stare:
<img width="359" alt="povodne" src="https://github.com/bratislava/konto.bratislava.sk/assets/44317233/6fc5b922-a335-42e3-97a2-4f9f73607fb2">
Nove:
<img width="358" alt="upravene" src="https://github.com/bratislava/konto.bratislava.sk/assets/44317233/579d7607-3cca-469a-8de7-257f7165b5a0">
