### ISSUE TITLE
Čo ešte chýba na produkcii pred launchom SUR ziadosti

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#677]
1. Homepage: 
- aktuálne bannery (nové žiadosti + právnické osoby (ak je profil FO))
- mestské služby - úprava 4 vybraných dlaždíc

2. Celá sekcia Moje žiadosti

3. Mestské služby Fyzické osoby
- pridať 2 nové dlaždice
- písala som to aj v inom tasku, ale na produkcii máme veľmi okresané dlaždice pri fyzických osobách, nechápem prečo, prosím hodiť naspäť do verzie ako je to vo [Figme](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=6888-21075&mode=design&t=2C8vqfiKhBUofqHk-4)

4. Mestské služby PO a FO-p
- tu som si všimla len, že v prípade mestských služieb pre PO majú po úprave 2 posledné slaždice iné ikonky ako sú vo [Figme](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=8177-31311&mode=design&t=2C8vqfiKhBUofqHk-4) - Zaujatie a Určenie podmienok. Inak dobre, možme hodiť na produkciu.

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/da2059a9-af34-4cb7-b504-fc06f8c2190d)

**Comment by Balros** [comment]
Potreboval by som este info ku novym kachlickam `Zaujatie verejneho priestranstva` a `Určenie podmienok uvedenia komunikácie do pôvodného stavu`. Potreboval by som vediet do akej kategorie patria a kam maju linky smerovat.

**Comment by Balros** [comment]
Sieste od zaciatku a druhe od konca je ta ista kachlicka.

**Comment by MartinaMihalkovicova** [comment]
Zaujatie - prosím vytvorme novú kategóriu Verejné priestranstvo

Určenie - vytvorme novú kategóriu Doprava. Okrem Určenia sem hoďme prosím všetko z kategórií MHD a Parkovanie (a tieto dve zmažme)

- k tej istej kachličke - ostáva len na šiestom mieste od začiatku, upravila som aj Figmu

**Comment by Balros** [comment]
nech to tu mam pohromade:

- `Zaujatie verejneho priestranstva`- [link](https://bratislava.sk/mesto-bratislava/transparentne-mesto/majetok-mesta/zaujatie-verejneho-priestranstva) do novej kategorie `Verejné priestranstvo`
- `Určenie podmienok uvedenia komunikácie do pôvodného stavu` - [link](https://bratislava.sk/doprava-a-mapy/doprava/dopravne-povolenia) do novej kategorie `Doprava`
- vsetko z kategorii MHD, Parkovanie ide do kategorie `Doprava`
- kategoriu MHD, Parkovanie zmazat
- `Adopcia zelene` - [link](https://bratislava.sk/zivotne-prostredie-a-vystavba/zelen/udrzba-a-tvorba-zelene/adopcia-zelene)

**Comment by MartinaMihalkovicova** [comment]
Zaujatie verejného priestranstva mame zly link - je tam na konci navyse jedno "s", tak ahdze 404

https://bratislava.sk/mesto-bratislava/transparentne-mesto/majetok-mesta/zaujatie-verejneho-priestranstva = spravny link

Ostatne je super, dakujem :)

**Comment by MartinaMihalkovicova** [comment]
@Balros mestek sluzby pre PO maju stale zly link pri zaujati ako pisem v komentari vyssie
