### ISSUE TITLE
Scrollovanie pri erroroch

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#682]
Prosím, vieme spraviť to, aby keď mi niekde vyhodí error, tak ma prescrollovalo k danému erroru? Napríklad pri registrácii je to problém, keďže nemusím vidieť celý screen, dokola nám ľudia klikajú na button registrovať sa a nenapadne im úsť pozrieť hore na error hlášku, tým pádom potom nevedia, že je niečo zle. Navrhujem vždy prescrollovať na error, ktorý je na screene najvyššie (ak ich je viac).

**Comment by mpinter** [comment]
@MartinaMihalkovicova dopln prosim zariadenie / browser kde sa to deje. Vyskusane na iOs chrome a safari pri registracii, na oboch som prescrollovany na najvyssi error.

**Comment by MartinaMihalkovicova** [comment]
Deje sa mi to v Chrome na iOS, konkretne som skusala registraciu s rovnakym emailom s akym uz mam konto zalezene na 100% lupe. A stale mi to robi, error alert myslim, ktory ti v tomto pripade vyhodi, nie error vo fielde.
