### ISSUE TITLE
Chýba označenie Neoverený profil v hlavičke konta

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#701]
Označenie Neoverený profil z hlavičky konta vedľa iniciáloch má po správnosti fungovať takto: 

neovereny ale neskusal sa overovat - ukazeme badge
neovereny skusal sa overovat ale je v queue - neukazeme badge
neovereny skusal sa overovat ale zamietnuty - ukazujeme badge

Momentálne je nesprávne pripad, kedy nezobrazujeme hlasku ked sa skusal overit ale BE zamietol overenie (z roznych dovodov)

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/148b012c-2291-4e73-a79c-05df2a1c99cb)

**Comment by Balros** [comment]
Toto nastava uz len v pripade ze user sa dal overit a je v procese overovania, tzn ze je v podivnom medzistave.

**Comment by Balros** [comment]
Po dohode s @MartinaMihalkovicova:
- neovereny ale neskusal sa overovat - ukazeme badge
- neovereny skusal sa overovat ale je v queue - neukazeme badge
- neovereny skusal sa overovat ale zamietnuty - ukazujeme badge

**Comment by MartinaMihalkovicova** [comment]
@Balros toto nie je nahodou uz done?
