### ISSUE TITLE
Field Katastrálne územia

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#702]
Prosím, vráťme do dropdownu fieldu Katastrálne územie všetky katastrálne územia. V nejakom bode to bolo zrazu prepísané na mestské časti, len to nie je úplne to isté. Niektoré MČ majú viac katastránych území. Vyznačila som boldom 3 chýbajúce, prosím pridajme ich v tomto poradí, nech je to podľa abecedy. Máme tento field v oboch žiadostiach.

Čunovo
Devín
Devínska Nová Ves 
Dúbravka 
Jarovce 
Karlova Ves 
Lamač
**Nivy** 
Nové Mesto 
Petržalka 
Podunajské Biskupice 
Rača 
Rusovce 
Ružinov 
Staré Mesto 
**Trnávka**
Vajnory
**Vinohrady** 
Vrakuňa 
Záhorská Bystrica

+ prosím dajme do heltextu na koniec za vetu . (bodku)

**Comment by Balros** [comment]
tento pan ti bude vediet najlepsie odpovedat
<img width="963" alt="Screenshot 2024-01-12 at 16 44 34" src="https://github.com/bratislava/konto.bratislava.sk/assets/6770524/dd94eea4-4efe-450b-a603-edc60125bbe5">

**Comment by MarekBodingerBA** [comment]
@mpinter

**Comment by MarekBodingerBA** [comment]
Na STG to vidím.

**Comment by MartinaMihalkovicova** [comment]
Už vidím, kde je chyba. Je to upravené len v https://city-account-next.staging.bratislava.sk/mestske-sluzby/zavazne-stanovisko-k-investicnej-cinnosti/cdd309f9-1ee1-4084-bad6-46e5eb26d9a9#informacie-o-stavbe, malo by to byť upravené v oboch formulároch aj v: https://city-account-next.staging.bratislava.sk/mestske-sluzby/stanovisko-k-investicnemu-zameru/ba81e22f-5b94-4ada-bb8f-be798f296534#informacie-o-stavbe :) Viete prosím ešte upraviť?

**Comment by MartinaMihalkovicova** [comment]
chyba č.2: prosím doplniť tú bodku v oboch ziadosiach pod field, píšem to v tasku

**Comment by mpinter** [comment]
@MartinaMihalkovicova uz by to malo byt v poriadku, na stagingu aj na produkcii, pri oboch formularoch
