### ISSUE TITLE
BUG Možnosť vymazať v možnostiach žiadosti

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#703]
Možnosť vymazať má byť v žiadosti len v prípade, ak som otvorila koncept a prišla na žiadosť z Konceptov. Napriek tomu, že som išla na žiadosť cez dlaždicu v Mestské časti, ukazuje mi ju, nemalo by to tak byť. 

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/0b5416f2-5bef-4cc6-a92a-7de263a6eff1)

**Comment by mpinter** [comment]
Pred tymto si niekde spisme ako sa maju spravat koncepty (kedy vznika koncept a kedy nie) - napr ak to bude vzdy tak ze koncept vznikne az ked ho clovek manualne ulozi tak by som toto mozno rad vycistil aj na BE, nie len skryl moznost v menu.

**Comment by MartinaMihalkovicova** [comment]
Rozumiem, ale v tomto prípade sa nebavíme o koncepte. Toto je otvorenie novej žiadosti

**Comment by mpinter** [comment]
Medzitym vyriesene
