### ISSUE TITLE
chýba badge pri neoverenom profile

### ISSUE THREAD

**Issue by Balros** [bratislava/konto.bratislava.sk#705]
v headeri chýba badge, v profile vidím, že ide o neoverený profil

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/126803521/6a51cba3-8814-4708-930a-d1a9c1144b7b)

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/126803521/68827560-14eb-4989-a8e9-d21962ca636a)

**Comment by marykosticka** [comment]
zatváram, kvôli duplicitnému tasku https://github.com/bratislava/konto.bratislava.sk/issues/701
