### ISSUE TITLE
Ginis - vrámci klikačky chceme priradiť aj typ dokumentu

### ISSUE THREAD

**Issue by marykosticka** [bratislava/konto.bratislava.sk#710]
Aktuálny stav: v Ginise priraďujeme typ dokumentu "ESBS - dosla posta"
Želaný stav: pri záväzných stanoviskách chceme priradiť "e-ZST, žiadosť", pri SIZ zase "e-SIZ, žiadosť"

ak to vieme spraviť jedným vrzom, tak môžeme aj registratúrnu značku : TE7 (záväzká), TW1 (SIZká)

**Comment by marykosticka** [comment]
@mpinter pls, toto si nejako riešil?

**Comment by mpinter** [comment]
@marykosticka ak si spravne pamatam tak nie, pozriem na to v priebehu tohto tyzdna

**Comment by mpinter** [comment]
Zatvaram - ak tak budeme riesit odstranenim klikacky.
