### ISSUE TITLE
[Moje ziadosti] BUG - Odoslané vs Odosiela sa

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#725]
Po odoslaní žiadosti mi ju správne ukázalo v Odoslané. CCa po 10 minútach ju prehodilo do Odosiela sa, napriek tomu mi ostalo pri tabe Odoslané (1) a pri Odosiela 0 žiadostí. 

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/d08fb8e3-0600-4c77-a77c-12ea19f0b3ee)
![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/4959b39d-75a4-4d6f-aeca-86630d5b1159)

Akonáhle to prešlo do tabu Odosiela sa, ukázalo mi to Odoslanie neúspešné. O ďalších 10 min to prešlo späť do Odoslané a zmenilo to stav na Doručené.

**Comment by erehulka** [comment]
Tu asi potrebujem znalosť ako sa na frontende rozdeľuje do týchto tabov. Môj odhad je, že sa nepodarilo odoslanie na NASES, nastavil sa `FormError` na `NASES_SEND_ERROR` ale stav ostal v `QUEUED`.

Pozrel by som si logy čo sa vlastne stalo, @MartinaMihalkovicova máš pls id tohoto formuláru? Aj keď to je už pár mesiacov 😅

**Comment by Balros** [comment]
@mpinter toto by som zatvoril, ked tak sa otvori znovu, teraz je situacia taka ze su rozne datove zdroje pre cisielko v taboch a data v otovrenom tabe -> rozdiel v tychto datach moze byt par sekund no tato chyba co pise matka bola trvala a este pred sucasnym riesenim. Myslim ze aj tak sa to cele vyriesi ked zjednotite zdroj a budete si posielat meta data z ktorych sa doplnito cislo v hlavicke

**Comment by erehulka** [comment]
Toto je divné, pravdepodobne to bolo odvtedy fixnuté, išlo predpokladám o nejakú nezrovnalosť stavov. Tento formulár má v DB hodnoty:
- `state: ERROR`
- `error: GINIS_SEND_ERROR`
- `ginisState: FINISHED`

Čo sa nemôže dnes stať, lebo ginisState: FINISHED sa nastavuje jedine tu:
```ts
await this.prismaService.forms.update({
  where: { id: form.id },
  data: {
    state: FormState.PROCESSING,
      ginisState: GinisState.FINISHED,
      error: FormError.NONE,
  },
})
```

a po tomto sa dnes už formulár nemôže dostať do error stavu `GINIS_SEND_ERROR`.

Ja by som teda toto zavrel @mpinter
