### ISSUE TITLE
[Moje ziadosti] BUG - Moje žiadosti Odosiela sa zlý button

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#744]
2 žiadosti, ktoré som odoslala mi hodilo do Odoslanie neúspešné, tab Odosiela sa. To je správne, ak neprešli. Čo je ale zle, je že mám pri nich button Upraviť, napriek tomu, že s nimi nič neviem robiť a keď naňho kliknem, žiadosť mi zobrazí v Read only mode. 
Button by mal mať v tomto prípade, keď s tým user nevie nič robiť, verziu Zobraziť a ikonku oka.
![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/6c82cfd9-d653-4778-83b8-089fe2157f9e)

**Comment by mpinter** [comment]
Čaká na https://github.com/bratislava/nest-forms-backend/pull/252, čo je blokované NASES fix prostredím.
