### ISSUE TITLE
Klik na Moje ziadosti

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#747]
Momentalne nam velmi dlho trva, ked kliknem v konte na sekciu Moje žiadosti, kym sa naozaj zobrazi. Vieme na toto pozriet prosim a skusit to zrychlit?

**Comment by Balros** [comment]
Riesene v ramci https://github.com/bratislava/konto.bratislava.sk/issues/608.

**Comment by MartinaMihalkovicova** [comment]
je to o kusok lepsie, i ked stale ked na to kliknem, tak to chvilu nevidim ako zakliknute :D

**Comment by Balros** [comment]
Caka na release https://github.com/bratislava/nest-forms-backend/pull/327

**Comment by mpinter** [comment]
Toto zatvaram - vieme to este zlepsovat ale dnesny stav good enough.
