### ISSUE TITLE
Úprava textu v sumári a v stiahnutom PDF

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#750]
Prosím upravme textík nasledovne, len doplníme stiahnutie: 

Stiahnutím, uložením a/alebo odoslaním Žiadosti výslovne vyhlasujem, že som sa oboznámil s podmienkami spracúvania osobných údajov Hlavného mesta ako prevádzkovateľa osobných údajov a beriem na vedomie, že ich spracúvanie je nevyhnutné na splnenie zákonných povinností Hlavného mesta v súvislosti s vybavením tejto žiadosti.

Treba to upraviť v sumári + v stiahnutom PDF, kde máme tento istý text.

Pôvodne to vyzerá takto:
![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/e6c006ef-6655-4dc9-ad42-e7ce76afe41c)

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/b876a917-0e80-41e4-b6b1-64222c5ab5f1)

**Comment by MarekBodingerBA** [comment]
@MartinaMihalkovicova toto chceme aj v tom novom PDF?

**Comment by MartinaMihalkovicova** [comment]
Ano, treba to mat vsade podla noveho znenia @MarekBodingerBA
