### ISSUE TITLE
Email na DZN BETA form daňovníkov

### ISSUE THREAD

**Issue by SlavomirOslej** [bratislava/konto.bratislava.sk#765]
https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=9591%3A3051&mode=design&t=3FevQqm4RdL8vpDP-1

**Comment by Balros** [comment]
@SlavomirOslej kam ma smerovat tlacitko "Vyplniť daňové priznanie"?
