### ISSUE TITLE
[Text] Doplniť helptext do fieldu pri overení identity

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#802]
Pridajme pod field RČ (aj pre FO aj pre PO) helptext: 

"Zadávajte s lomkou."

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/168a51ac-2fd6-4dea-91ff-412a6949705c)

**Comment by MarekBodingerBA** [comment]
@MartinaMihalkovicova Btw, správne je lomka:
> Lomka (nesprávne lomítko, lomeno) je interpunkčné znamienko (/).

https://sk.wikipedia.org/wiki/Lomka

**Comment by MartinaMihalkovicova** [comment]
@MarekBodingerBA super, vdaka, ze si si vsimol. Prehodme teda na "Zadávajte s lomkou."
