### ISSUE TITLE
Wrong filesize is displayed in forms file upload

### ISSUE THREAD

**Issue by MarekBodingerBA** [bratislava/konto.bratislava.sk#816]
![Image](https://github.com/bratislava/konto.bratislava.sk/assets/104828482/eeff6095-040c-47f4-a9e7-973bf716b4ef)

**Comment by jitka1997** [comment]
This issue is a case of the 1 MB debate: Is it 1048576 bytes or 10^6 bytes? There's no universal agreement, but our forms use  1 MB = 10^6 bytes formula.

**Comment by MarekBodingerBA** [comment]
We decided to postpone this because of the low priority.

**Comment by mpinter** [comment]
Myslim ze vieme lepsie stravit cas inde, zatvaram.
