### ISSUE TITLE
Redizajn vygenerovaných pdf

### ISSUE THREAD

**Issue by marykosticka** [bratislava/konto.bratislava.sk#819]

**Comment by marykosticka** [comment]
@erehulka pls, co treba este spravit preto, aby sme to mohli pushnut na produkciu?

**Comment by erehulka** [comment]
@marykosticka Riešime to ešte s Marekom, sú tam menšie errory

**Comment by erehulka** [comment]
@MarekBodingerBA vieme toto označiť ako done?

**Comment by marykosticka** [comment]
@MarekBodinger @mpinter toto nám prechádza už aj do Ginisu alebo to vieme stiahnuť iba z konta?

**Comment by mpinter** [comment]
@marykosticka
