### ISSUE TITLE
Zmena fieldov v ZST a SIZ formulári

### ISSUE THREAD

**Issue by marykosticka** [bratislava/konto.bratislava.sk#839]
Doslovné prekopírovanie požiadavky

**ZMENA PORADIA STEPPERA**
Prílohy dať miesto kroku 1 ako krok 6

**ZMENA POLÍČOK PRE ADDRESU**
Pokladáme za potrebné zmeniť názvy týchto políčok, keďže u našej služby nie je podstatná adresa trvalého pobytu/sídla firmy, ale práve adresa "doručovacia", kde si daný subjekt poštu chce vyzdvihnúť. Neutrálne ako "adresa" sme to mali nastavené aj pri vytváraní formuláru. 

Žiadate ako - Fyzická osoba - Adresa trvalého pobytu - zmeniť na "Ulica, popisné číslo"
Žiadate ako - Fyzická osoba – podnikateľ - Miesto podnikania - zmeniť na "Ulica, popisné číslo"
Žiadate ako - Právnická osoba - Adresa sídla - zmeniť na "Ulica, popisné číslo"

Do príloh prikladám prinscreeny

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/126803521/70539424-bac4-461c-8888-d42dccdaf5f3)

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/126803521/39229c59-4583-4291-8812-cb9e6a88debe)

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/126803521/c9644fdc-0b9d-4e85-9d53-6923175ce1a6)

**Comment by MartinaMihalkovicova** [comment]
upraviť po debate podla figmy: 
[https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---read[…]ype=design&node-id=9980-11526&mode=design&t=63SLUbOVeRpsxERM-4](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=9980-11526&mode=design&t=63SLUbOVeRpsxERM-4)

**Comment by MartinaMihalkovicova** [comment]
@jitka1997 tieto zmeny na stagingu v žiadostiach vôbec nevidím.
