### ISSUE TITLE
Chyba v emaily a stave žiadosti - výpadok NASESu

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#911]
Ahojte, 
našla som chybu v emaily a v Mojich žiadostiach, pri chybe v odoslanej žiadosti. 

Email prišiel správne, po 24hodinách, avšak neprišla správna verzia. Mala som dostať [tento mail](https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=6591-23154&mode=design&t=naebHHysNYsXtfYR-4), kde sa píše len o chybe, ktorú neviem upraviť a píšeme len o omeškaní. Miesto toho mi prišiel mail s buttonom opraviť chyby, ktorý by mal prísť len vtedy, ak je v mojej kompetencii úprava formuláru. Button "Upraviť žiadosť" bol zároveň neklikateľný.

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/0562bec8-0cde-4568-a5a8-cfcfeac5ff40)

Druhá chyba je na to nadväzujúca, žiadosť padla do stavu Odoslanie neúspešné a mala button "Upraviť". Napriek tomu, keď som na button klikla, dostala som sa len na view only žiadosti, nevedela som ju upravovať. Po správnosti som mala vidieť [tento stav](https://www.figma.com/file/FHBgHIHB62YJjPLZcFMQxZ/Bratislavske-konto%2C-ESBS---work-in-progress-(Ma%C5%A5a)?type=design&node-id=5047-8577&mode=design&t=jkJ2lehlvrsPTQL0-4), ale vyzeralo to takto: 

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/b47a9866-b584-4592-8214-1c09aefafccf)

Prosím, vieme, pozrieť, kde zlyhalo to rozlíšenie, ktorý email má prísť + ako je to so stavmi žiadosti?

**Comment by erehulka** [comment]
Fixol som ten použitý mail template, ale neviem prečo sa tam zobrazoval ten button upraviť. @mpinter aká je logika na frontende, že kedy sa tento button zobrazí? Resp. kde to viem nájsť vo FE zdrojákoch?

**Comment by erehulka** [comment]
Frontend Followup: #744

**Comment by mpinter** [comment]
👍 , issue ohladom emailu zatvaram ako hotovu.
