### ISSUE TITLE
Detail žiadosti - História zmien

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#914]
V detaile žiadosti (po rozkliknutí konkrétnej žiadosti v sekcii Moje žiadosti) nezobrazujeme správne časť História zmien. Jediný údaj, ktorý sem dotiahneme je, že Žiadosť bola doručená na magistrát. Potrebujeme, aby tu boli odzrkadlené všetky súčasné stavy,ktoré sa so žiadosťou dejú: 
- Žiadosť bola odoslaná. (stav: Odoslaná)
- Žiadosť bola doručená na magistrát. (stav: Doručená)
- Zamestnanci a zamestnankyne magistrátu pracujú na vybavení vašej žiadosti. (stav: Vybavuje sa)
- Žiadosť bola vybavená. (stav: Vybavená) / Žiadosť bola zamiestnutá. (stav: Zamietnutá)

Momentálny stav: 
![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/a2f213e3-714a-4e9b-8323-fdcc7a3979a9)

Želaný stav: 
https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=7124-22145&mode=design&t=RXaupotwnUlZWfTn-4

**Comment by mpinter** [comment]
sucastou https://github.com/bratislava/konto.bratislava.sk/issues/1642
