### ISSUE TITLE
CSS sticky header

### ISSUE THREAD

**Issue by MarekBodingerBA** [bratislava/konto.bratislava.sk#921]
Implementovať sticky header pomocou CSS, dnes je veľa vecí rozbitých:

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/104828482/c0db283e-4eff-4bd5-8d97-7af0a16582fb)
![Image](https://github.com/bratislava/konto.bratislava.sk/assets/104828482/d5f66558-2220-4c0c-90a1-6447e64a3f3d)
![Image](https://github.com/bratislava/konto.bratislava.sk/assets/104828482/3a3399d9-1024-4a2f-b910-895ec14374a4)

**Comment by MarekBodingerBA** [comment]
Status bar sa teraz skrýva po scrollovaní:
https://github.com/bratislava/konto.bratislava.sk/assets/104828482/12720998-850e-4ebc-9106-3627c2cc5b3a

**Comment by mpinter** [comment]
Mergnute a deploynute, zatvaram.
