### ISSUE TITLE
Chýbajúca error hláška a screen pri chybnom overení identity

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#933]
Schválne som zadala chybné údaje do overovania identity. Po prvý raz sa button len točil a následne zmazal polia a dotočil sa bez verdiktu. Klikla som na overiť znova s prázdnymi poľami a error hlášky sú nesprávne:

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/20ba936b-1c3f-4f7a-9fd0-b86711553a0f)

1. Má byť: IČO je povinné. 
2. Je ok
3. Má byť: Číslo občianskeho preukazu je povinné.

Ak sa nepodarí overenie, mala by sa zobraziť táto error hláška: https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/Bratislavske-konto%2C-ESBS---ready-for-dev-(Ma%C5%A5a)?type=design&node-id=652-76200&mode=design&t=0bQ1AsdxrFioqg9y-4

**Comment by jitka1997** [comment]
@MartinaMihalkovicova  
3. má byť "Číslo občianskeho preukazu je povinné" aj keď do toho poľa sa môže písať aj číslo dokladu o prechodnom pobyte?

**Comment by MartinaMihalkovicova** [comment]
napíšme teda prosím len "Číslo je povinné."
