### ISSUE TITLE
BUG - Detail podania - Posledná zmena

### ISSUE THREAD

**Issue by MartinaMihalkovicova** [bratislava/konto.bratislava.sk#956]
Napriek tomu, že posledná zmena stavu na Vybavené sa udiala v apríli, v detaile ziadosti mi datum poslednej zmeny dotahuje ako datum dorucenia. 

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/3d4e4b63-1622-4af7-850b-52e90dc7653a)

![Image](https://github.com/bratislava/konto.bratislava.sk/assets/132052087/268c4df6-3585-4d43-a7de-cb42030b52fe)

**Comment by mpinter** [comment]
Closing in favour of https://github.com/bratislava/konto.bratislava.sk/issues/1642
